#+TODO: QUESTION LEARNING | LEARNED SMALLQ

* Математика
  Матанализ
** LEARNED 1) Предел числовой последовательности, теорема Вейерштрасса о пределе монотонной последовательности
*** LEARNED [#A] Определение предела, определение отрицания предела
    Стандартное, через e. Отрицание предела - ∃e>0 что за него последовательность хоть где-то да выйдет
*** LEARNED Лемма о единственности предела последовательности
    a и b - два предела одной последовательности. Рассмотрим непересекающиеся окрестности - когда-нибудь последовательность зайдет
    и туда и туда, что бред
*** Последовательность ограничена с n0 → ограничена везде
    После ограничена, а до - возьмем супремум и инфиум конечной части
*** Сходящаяся последовательность ограничена
    Начиная с какого-то n для ϵ = 1 по определению оно огр. a ⨦ 1, поэтому верно по предыдущей лемме.
*** Последовательность нснм по модулю больше половины своего предела, причем с сохранением знака
    a > 0 - предел. Рассмотрим ϵ = a/2. По определению - раскроем модуль и получим то, что надо. Потом для a < 0 так же.
*** Лемма о сохранении знака - знаки предела и посл. совпадают начиная с какого-то n
    прямо следует из предыдущей
*** Определение бесконечно-малой последовательности (бмп). Любую посл. м. представить как сумму ее предела и бмп.
    рассмотрим бмп = последовательность - предел. Покажем по опр, что она - бмп.
*** [#B] бмп + бмп = бмп.
    для любого ϵ можем выбрать общий (max) n0, что они обе меньше ϵ\2. => сумма < ϵ
*** бмп * огр = бмп, бмп*С = бмп, бмп*бмп = бмп
    1) пусть огр < C, тогда бмп нснм < ϵ/c. => произведение < ϵ
    остальное сразу следует из 1.
*** Предел суммы, произведения и частного (b != 0) равен сумме, произведению и частному пределов
    Везде сначала раскладываем последовательность на сумму предела и бмп, потом 
    1) a + b + бмп = a+b
    2) все - бмп, кроме a*b
    3) Берем n после которого yn != 0. Пишем xn/yn -a/b, выносим 1/yn, получаем огр*бмп.
*** LEARNED (предельный переход в неравенстве) Если нснм xn <= yn, то и a <= b.
    1) от прот: рассм. непересекающиеся окр. a и b. нснм последовательности зайдут в свои окрестности и будет противоречие: xn>yn.
*** (Лемма о двух мажорантах) limXn = limYn = a, Xn <= Yn <= Zn => limYn = a.
    Фиксируем e. Тогда рассмотрим n, когда Xn и Zn уже в этой окр. Соответственно, Yn тоже зажата м-у a-e и a+e начиная с этого n =>
    limYn = a по опр.
*** LEARNED [#A] (Т. Вейерштрасса) монотонно возр и огр сверху => имеет предел равный sup. // Аналогично для убывает и inf
    Вспомогательное утверждение: у любого непустого, огранниченного сверху/снизу, множества, есть точная верхняя/нижняя грань.
    Если у мн-ва X есть наибольший элемент -> он sup
    Если нет => сечем R так, что A' - все верхние грани Х, A - все остальные. По теореме Дедекинда ] либо наибольшее в а, либо наи-
    меньшее в A'. => первое не подходит, а второе - то, что надо.

    Рассм. α = supXn. ∀e > 0 ∃n ∀nk > n: a-e < Xnk ⩽ a (ибо возр). => нснм Xnk ∈ Ue(a) => a - предел по опр.
** LEARNED Вспомогательные штуки
*** LEARNED Теорема Кантора о вложенных отрезках: вложенные отрезки имеют как минимум одну общую точку. А если их длины убывают - единственную.      
    Влож отрезки: ...[an, bn] ∈ ... [a1, b1] → a1 <= a2 <= .. <= an ... <= bn <= ... <= b1. Рассмотрим посл. {an} и {bn}. 
    an огр. сверху любым b, bn огр снизу любым a => существуют supAn = γ1 и infBn = γ2. [γ1, γ2] - принадлежит всем отрезкам.
    Теперь, если |an - bn| → 0 => an ⫹ γ1 ⫹ γ2 ⩽ bn => γ1 = γ2 = γ = limAn = limbn по т. Кантора
 
*** 6 стандартных предельных символов (6 СПС)
    a, a+0, a-0, +∞, -∞, ∞
** LEARNED 2) Частичный предел числовой последовательности. Теорема Больцано-Вейерштрасса
*** [#A] Опр. частичного предела последовательности Xn
a - ч. пр, если ∃ Xnk - строго возр подпосл. такая, что limXnk = a.
*** Предел любой подпоследовательности равен пределу последовательности, если он есть
Рассматриваем U(a ∈ СПС). Внутри - если посл зашла, то подпосл тоже. Вне окр - конечное число эл-тов.
Следствие - если предел ∈ R, то он же - единственный ч. пр.
*** LEARNED (Критерий ч.пр) a ∈ (R, +∞, -∞) - ч.пр. Xn <=> в любой Ue(a) Xn ∃ беск. число членов Xn
=> Если оно ч.пр, то вне любой окрестности содержится не более, чем конечное число членов ряда => внутри окрестности все остальные(∞)
<= Строим подпосл: Xk1 ∈ U1(a), xk2 ∈ U_1/2(a) ... т.к. в любой окр содержится ∞ членов, то мы всегда возьмем один - беск посл
со строго возр. индексами. Т.к. Xkt ∈ U_1/t(a) => a - 1/t ⩽ Xkt ⩽ a + 1/t => по лемме о двух мажорантах limXkt = a. 
Для беск. нужно брать //доделать 
*** LEARNED [#A] (т. Больцано-Вейерштрасса) Любая огр. посл. имеет сх. подпосл.
Xn - огр => лежит в отрезке [a, b]. Разобьем отрезок пополам и возьмем ту половину, где Xn - бесконечно много (если в обоих
бесконечно много - то любую). И так рекурсивно. μ[An, Bn] = (b-a)/2^n -> 0 => по т. Кантора есть ровно одна общая точка c.
Фиксируем e. Т.к. ∃n0, что ∀n>n0 μ[An, Bn] < e (=> ∈ Ue(c)), причем там ∞ Xn, то по критерию ч.пр. с - частичный предел.
*** LEARNED (о единственном ч.пр) Xn - огр и имеется ровно 1 ч.пр. =a, то Xn -> a. 
Xn - огр => Xnk - огр => a ∈ [m, M]. Пусть a - не предел Xn, =>  ∃ e>0, что вне Ue(a) б.м. членов Xn (пусть справа) => по ТБВ
на [a+e, M] имеется частичный предел => противоречие тому, что он один.
** LEARNED 3) Критерий Коши сходимости последовательности
*** (Критерий Коши) Xn - сх <=> Xn - фунд.
=> пусть a - предел. Фиксируем e, тогда ∃n0, что | | < e/2. Берем n>n0 и m > n0: |xn -xm| = |(xm - a) + (a - xm)| <... < e.
<= Докажем, что оно огр: фиксируем e = 1, тогда ∃n0, ∀n, m ⩾ n0 |xm - xn| < 1 Фиксируем m = n0 => |xn| ... < 1 + |xn0| => огр 
начиная с n0 => огр везде => по ТБВ ∃ ч.пр. Чтобы доказать, что он - предел всей Xn, докажем, что он один. 
От противного, пусть их два: b > a. Пусть e = (b-a)/3 (из опр. фунд) => ∃n0, что |xn - xm| < e. Но т.к. вокруг каждого предела
бесконечно много элементов Xn, то найдутся n1, n2 > n0, что Xn1 ∈ Ua, Xn2 ∈ Ub => противоречие, ибо между окрестностями зазор > e.

** LEARNED 4) Опеределения предела функции по Коши и по Гейне, их эквивалентность. Критерий существования предела по Коши. 
*** LEARNED Определение по Коши 
limf(x) = b при x->a :=  ∀e > 0 ∃δ(e)>0 |x-a| < δ => |f(x) - b| < e
*** LEARNED Определение по Гейне
-//- := ∀Xn: limXn = a => limf(Xn) = b при n -> ∞
*** LEARNED Эквивалентность Коши и Гейне
=> Возьмем {Xn} такую, что limXn = a (xn ≠ a). Зафиксируем e, подберем такой номер n0, что ∀n>n0 |xn-a| < δ. Но из этого следует,
что |f(xn) - b| < e. В силу произвольности Xn, это предел по Гейне.
<= Возьмем отрицание Коши: существует e, что какую бы δ мы не взяли, найдется U(a), что f(x) !∈ U(b)
Пусть δ = 1/n => есть {Xn}, что ∀n ∈ N Xn в 1/n-окрестности a, но при этом f(Xn) вне e-окрестности b. По лемме о двух мажорантах, 
limXn = a => по гейне limf(xn) = b. Делаем предельный переход - получаем противоречие.
*** Много переходных лемм, аналогичных билету 1.
Доказательства в духе: возьмем рандомную подпоследовательность, воткнем ее в наши функции и рассмотрим это как новые последовательности.
По соответствующим леммам, для последовательностей работает => для функций работает в силу рандомности последовательностей.
*** LEARNED (Критерий Коши существования предела функции) Функция имеет предел b в точке a <=> функция "фундаментальна в точке a"
=> Из предела по Коши берем x1 и x2 из δ-окрестности такие, что |f(x1 и x2) - b| < e. Дальше |f(x1)-f(x2)| = |f(x1) - b.... | <...<e   
<= Возьмем Xn такой, что limXn = α и покажем, что f(xn) - фундаментальна (используя усл-е) => имеет предел.
Теперь докажем, что произвольно взятые Xn будут иметь один и тот же предел. Пусть нет: Xn->α, Yn->α, но f(Xn)->a, f(Yn)->b. 
Склеим Xn и Yn (x1, y1...) , получим Zn -> α. Но у него не будет предела, ибо есть два частичных предела. Противоречие.

** SMALLQ 5) Свойство непрерывной функции на отрезке, т. Вейерштрасса и Больцано-Коши
*** QUESTION Что такое свойства?
*** Непрерывность на отрезке [a, b] => непрерывность во всех точках интервала (a, b), непрерывна справа в a, и слева в b
*** (Первая т. Вейерштрасса) f - непр. на [a, b] => f - огр на [a, b]
Пусть это не так: тогда ∀e>0 ∃x ∈ [a, b] f(x) > e. Будем подставлять e = 1, 2, 3..., получим {xn} такую, что |f(xn)|>n. 
Xn ∈ [a, b] - огр, тогда ∃Xnk - сх. (пусть к точке x0 ∈ [a, b] т.к. xnk ∈ [a,b]). f - непр => lim(f(Xnk)) = f(x0). Но, при этом, 
f(Xnk) > nk >=k (как возр. индексы подпосл). => f(Xnk) -> ∞ при k -> ∞. Противоречие.
*** (Вторая т. Вейерштрасса) f - непр. на [a, b] => f достигает своих sup и inf на [a, b]
Sup и inf существуют (ибо f - огр по Вейерштрассу1). Пусть sup = M. Тогда ∀M'<M ∃x: f(x)>M'. Будем подставлять M' = M-1/n, 
получим последовательность Xn ∈ [a, b] => ∃ Xnk - сх к X0. но т.к. ф-я непрерывна в x0, то limf(Xnk) = f(x0) при k->∞. 
Но f(Xnk)->M, так что f(x0) = М в силу единственности предела.
*** (т. Больцано-Коши) f - непр. на [a, b] и f(a)*f(b) < 0 => ∃c ∈ [a, b], что f(c) = 0
Рекурсивно делим отрезок пополам и смотрим значение в середине: если 0 - ок, если нет, то берем тот отрезок, на концах
которого f принимает значения разных знаков. Получим набор вложенных отрезков, длина которых = (b-a)/2^n -> 0. По т. Кантора,
существует ровно одна точка с общая для этих отрезков. Докажем, что f(c)=0:
От противного, пусть f(c)>0, например. Тогда существует окрестность точки с, в которой f > 0. Половинным делением мы когда-нибудь
загоним наш отрезок в эту окрестность => противоречие, ибо он разного знака на концах.

** LEARNED 6) Дифференцируемость функции одного переменного, теорема Ферма, Ролля, Лагранжа и Коши
*** (Теорема Ферма) Если у функции в точке локального экстремума (в.г, нестрогого) существует производная, то она конечна и равна 0.
Рассмотрим максимум (минимум - аналогично). Запишем производную слева и справа по определению. Заметим, что эти пределы разных
знаков, но т.к. функция непрерывна в точке, то пределы слева и справа равны => оно может быть только 0.
*** Дифференцируемая функция на промежутке
Для каждой точки промежутка существуют конечные производные, а для концов - если они принадлежат - соответствующие односторонние 
производные.
*** Дифференцируемая в широком смысле функция на промежутке
    То же самое, только производные м.б. +-∞
*** (Теорема Ролля) Если функция непр. на [a,b], дифф на (a, b) и f(a) = f(b) то ∃x ∈ (a, b) что f'(x) = 0
На отрезке достигается минимум и максимум (2 т.В). Если на границах - то функция константа и подойдет любая точка. Если нет,
то ∃x, что f(x), допустим, sup. Тогда по т. Ферма f'(x) = 0.
*** (Теорема Коши) f,g - непр. на [a, b], f - д.в.ш.с на (a, b), g - дифф на (a. b), причем g'(x) ≠ 0, то ]x: (f(b)-f(a))/(g(b)-g(a) = f'(x)/g'(x)
Расcм: ϕ(x) = f(x)+λg(x), λ ∈ R. Подберем λ так, что ф(а)=ф(b). => λ = - (f(b)-f(a))/(g(b)-g(a)). g(b) ≠ g(a) нигде, ибо иначе бы
по т.Ролля где-нибудь была бы ненулевая производная. ф - непр и дифф в широком смысле, ибо лин.к. дифф(g) и д.в.ш.с(f).
В общем, мы в условиях т. Ролля для ф(x) => ∃t: ф'(t)=0 = f'(t) + λg'(t) => λ = -f'(t)/g'(t) => то, что надо.
*** (Теорема Лагранжа) f - непр. на [a, b], д.в.ш.с на (a, b) => ]t: f(b)-f(a) = f'(t)(b-a)
Верно по т. Коши для g(x) = x.

** QUESTION 7) Тейлор для одного действительного переменного
*** Формула Тейлора
это не буду переписывать, и так знаю
*** (Остаток в форме Пеано: корректность) (r_n(f, x) = o((x-x0)^n) при x→x0
Л1) P'n(f, x) = Pn-1(f', x), r'n(f, x) = r(n-1)(f',x) - раскрывая в лоб
Л2) P^(k)_n(f,x0) = f^(k)(x0), r^(k)_n (f, x0) = 0 - первое исходя из того, что ∑(j=k..n) не 0 только при j=k. Второе отсюда же.
Т) По индукции. Пусть f имеет конечную производную в т. x0 до n+1 включительно, и при этом для n мы знаем утверждение теоремы.
Т.к. f имеет конечную n+1 произв, то f' имеет конечную n произв => по предп. индукции r(f', x) = o((x-x0)^n).
Т.к. f имеет конечную n+1 произв, то в некоторой окр. x0 она непр, + дифф в x0 => r_(n+1)(f, x) -дифф в x0 (как разность f и P)
Зафиксируем точку х и применим теорему Лагранджа на [x, x0] (или [x0, x], смотря что больше). Получим f(x)-f(x0) = r'(e)(x-x0)
e зависит от x, поэтому оно e(x). Так же e(x)->x0 при x->x0 (т.о 2 маж). Дальше хитрый переход на стр. 165.  
*** (Остаток в форме Пеано: наилучшее приближение) Если f = Q + o((x-x0)^n) при x→x0, то Q = Pn(f,x) 
по предыдущей теореме, f = Pn + o(..). Тогда T = P-Q = o((x-x0)^n). Докажем, что это нулевой многочлен.
Т.к. оно o(...^n), то lim(T(x+t))/t^n)->0 при t->0 => T(x+t)->0 при t->0 => a0 = 0. => T = a1*t + ...+an*t^n
Разделим на t, получим что a1 = 0 и так далее занулим все коэффиценты.
*** QUESTION Остаток в форме Лагранджа
** LEARNED 8) Предел, неёпрерывность, ч.пр. и дифференцируемость функции нескольких переменных.
*** (Предел функции нескольких переменных по Коши) Все то же самое, только x, a ∈ R^m, | | - норма в R^m
*** (Предел функции нескольких переменных по Гейне) То же самое, только посл-ть ∈ R^m и сходится по норме. 
*** (Предел функции в точке по множеству) 
По Гейнe: a-пр.т.X, ∃U(a) f-опр на U∩X, тогда limF(x)=b при x->a,x∈X := вып-cя ∀xn∈X: limxn=a, xn≠a 
По Коши: то же самое, что и обычное определение, только x∈U(a)∩X
*** (Непрерывность) f - непр-а в а, если опр. в нек. окр. а и limf(x)->f(a) при x->a
*** (Непрерывность на мн-ве) то же самое, только предел по множеству.
Изолированная точка - непрерывна по определению
*** (т. о промежуточных значениях) Непр. функция принимает все значения между значениями в начале и конце.
f(x1)=y1, f(x2)=y2. x1,x2 ∈ G - откр. Рассмотрим кривую Г ∈ G, соединяющую x1 и x2: Г=(a1(t), a2(t)...an(t)), t∈[a,b].
ф(t) = f(a1(t),...an(t)) - непр на [a, b], ф(а)=y1, ф(b)=y2 => по аналогичной теореме для функции одной переменной все работает.

*** (обобщение т. Вейерштрасса 1,2) f - непр на компакте ограничена на нем и достигает своих sup и inf.
доказательство ровно такое же, с точностью до замены модуля на норму и R на R^m
*** (Частная производная)f: опр в окр. x0  и имеет кон. произв. в x0 f'x в точке (x0, y0) = df(x, y0)/dx в т. x0
*** (Дифференцируемая ф-я)f - дифф в x0 ∈ R^m, если можно представить: δf(x0) = f(x0+δx) + A(δx) + α(δx)*|δx|
А - линейная часть - дифференциал - df(x0)
α - бм при δx->0 
*** (НУ Дифференцируемости) f - дифф в x0 => 1) f - непр в x0, 2)∀(i=1..n) ∃кон. ч.пр. df/dxi(x0)
1) следует из того, что при δx->0 f(x0+δx)->f(x0) - опр. непрерывности
2) (док-во для сущ. ч.пр. по первому аргументу)
// будем вносить дельту только в первый аргумент, поэтому перепишем все для одного аргумента (α->β, A->A1, Δx -> Δx1)
Зафиксируем δx = (δx1, 0, 0, ...) и перепишем b(δx1) = α(δx1, 0 ...)*sign(δx1) (заметим, что b(δx1)->0)
 => производная перепишется в виде: f(x0 + δx, x1,....) = f(x0, x1...) + A1*δx1 + b(δx1)*δx1. Перенесем f, разделим на δx1 и
устремим его к 0 => получим производная = A1 по определению
*** (ДУ Дифференцируемости) есть ч.пр по всем переменным, и все непр в x0 => f - дифф в x0.
Распишем δf(x0, y0), сделаем +-f(x0+δx, y0), применим т. Лагранджа для x и y, получим = f'x(x~, y0)*δx + f'y(x+δx, y~)*δy. (*) 
Заметим, что при δ(x,y) -> 0 x~->x0, y~->y0. => f'x(x~, y0)->f'x(x0, y0) = A (в силу непрервыности) // для f'y = B - аналогично
Подставим в (*), получим δf = (A*δx + a(δx)*δx) + (B*δy + b(δy)*δy). Мелкие = o(p) => определение дифференцируемости
** LEARNED 9) Равномерная непрерывность функции на мн-ве, теорема Кантора
*** Равномерно-непрерывная функция: Если ∀e>0 p(x1 x2)<δ => |f(x1)-f(x2)|<e
*** (т. Кантора) f - непр. на компакте, равномерно-непрерывна на нем
От противного: пусть не равномерно-непрерывна, тогда существует e, что какие-бы δ: p(x1,x2)<δ мы не взяли, |f(x1)-f(x2)|>e
Будем подставлять δ=1, 1/2, 1/3, получим {x'k}, и {x''k}, что p(x'k, x''k)<1/k но |f(x'k)-f(x''k)| >  e.
Огр полследовательность x'k имеет сх. подпосл x'kk, которая сходится к x0∈G (ибо либо внутренняя, либо гр, но границы входят в компакт)
x''k тоже имеет сх подпосл x''kk
p(x''kk, x0) по пр. треуг ⩽ p(x''kk. x'kk) + p(x'kk, x0) = 1/k + 0 (при k->∞) => limx''kk->x0 => lim(p(x''k-x''kk))->0 при k->∞
Противоречие, ибо для подпоследовательностей, как для части последовательности, p(x''k-x''kk)>e.

** LEARNED 10) Определенный интеграл Римана одного переменного, критерий интегрируемости Дорбу.
*** Разбиение отрезка R - оно же дробление
*** Дробления упорядочены с помощью ∈: R1>R2 если все точки R2 присутствуют в R1 и еще добавили новые
*** R = Max(R1, R2) := R1 ∪ R2. Естесственно, R > R1, R > R2
*** Дальше все делается для функции f, ограниченной на [a, b]:
*** Mi = supf(x) на [xi, x(i-1)]. mi - inf, wi = Mi-mi - колебание ф-ции на отрезке.
*** Верхняя сумма Дорбу: S*_R := ∑Mi*δxi, Нижняя S_*R := ∑mi*δxi, wR = S*_R-S_*R
*** Лемма: R1>R2 => S*_R1 ⩽  S*_R2, S_*R1 ⩾ S_*R2, w_R1 ⩽ w_R2
Доказываем 1. Второе - аналогично, третье - как разность первого и второго.
По индукции: докажем, что верхняя сумма уменьшится при добавлении одной точки в дробление. Это очевидно: мы раздробили один 
отрезок новой точкой пополам, тогда теперь у половинок ступенек супремумы стали разные, а раньше был общий => одна из них не 
увеличилась.
*** Верхний интеграл Дорбу I* := инфиум верхних сумм. Нижний I_* := супремум нижних.
*** Если I*=I_* => f - интегрируема по Риману, а значение I* - определенный интеграл Римана функции f на [a, b]
*** (Критерий интегрируемости Дорбу)
Равносильно:
1) f - интегр. по Риману на [a,b]
2) ∀e>0 ∃R: wR<e
3) ∀e>0 ∃δ ∀R: мелкость < δ => wR<e

3=>2 - очевидно
2=>1 - wR = S*-S_*<e а верхний и нижний интегралы Дорбу зажаты между суммами => интегралы стремятся друг к другу => интегр по риману 
1=>2 - Возьмем дробление R1 такое, что верхняя сумма отстает от интеграла не более, чем на e/2. Возьмем R2 для нижней суммы так же
Возьмем R := max(R1, R2), при R верхняя и нижняя сумма приблизятся к графику сильнее => не вылезут за I+-e/2. Отнимем дробления
друг от друга, получим то, что надо.
2=>3 У нас есть, что ∀e>0 ∃R: wR<e → ∀e ∃ R0: wR0 < e/2  
Пусть δ0 - мелкость дробления R0, N0 отрезочков внутри. Возьмем новую δ := min(δ0, e/4MN0). Возьмем R - произвольное дробление с 
мелкостью не больше δ. Наложим R1 на R0. Часть отрезочков R1 точки R0 разрубят на 2 части (таких не более N0-1). Рассмотрим 
wR1 = ∑wi*δxi = ∑' (по всем целым из R1) + ∑'' (по всем, которые разрубило точками из R0). Оценим сумму.
1) Рассмотрим R = max(R1, R0). R>R0 => wR ( = wR1 на ∑') ⩽ wR0 < e/2.
2) ∑'' < ∑(число столбиков = N0)*(макс. длину = δ)*(макс. wi = Mi-mi < 2M) = e/2.
Сумма меньше e. ЧТД.
** LEARNED 11) Криволинейный интеграл первого и второго рода функции нескольких действительных переменных.
*** Интеграл 1 рода
Пусть Г - гладкая кривая r(t) = (x(t), y(t), z(t)), t ∈ [a,b], G ∈ R^3, Г ∈ G. f - непр на обл. G. 
Тогда криволинейным интегралом 1 рода ∫гf( x,y,z)ds наз-ся определенный ∫ Римана: ∫(a,b)f(x(t),y(t),z(t))*|r'(t)|dt.
*** Допустимая замена параметра в кривой
Пусть кривая Г параметризуется двумя способами: (x1(t),y1(t),z1(t)) t ∈ [a,b] и (x2(u),y2(u),z2(u)), u ∈ [α,β]. При этом u(t) - 
это непрерывно дифференцируемая функция на [a, b], отображающая [a, b] на [α, β], то такая замена называется допустимой.
*** (Корректность) Значение ∫ не изменится при ДЗП
У нас есть ДЗП ровно такая, как выше. Замена взаимооднозначна по т.Б-К (многомерная): u' либо >0 везде либо <0 везде.//недопонял 
Выпишем два интеграла для обоих путей. Потом во второй (который c u) поставим замену u->u(t), t∈[a,b]. Выпрыгнет u'(t)dt в конце
и +- перед ∫ - + соответствует u'(t)>0, минус - u'(t)<0. 
Соответственно, запихиваем безболезненно u'(t) под модуль и получаем первый интеграл.
*** Свойства ∫ 1 рода - линейность и аддитивность по кривой
**** Ориентация кривой - гладкая кривая ориентирована, если задан единичный вектор r(t) - непр на [a,b] 
то есть если сделан выбор знака в равенстве r = +-r'(t)/|r'(t)|
*** Кусочно гладкая кривая
кривая, на всех своих кусках гладкости ориентированная так, что конец i-1 куска - это начало i куска. 
*** Интеграл второго рода
Пусть Г - ориент. гладкая кривая (r(t) - ед.век.кас.к Г, он же - ориентация Г), G ∈ R^3, Г ∈ G. a:G ∈ R^3->R^3 - непр.
Тогда криволинейным интегралом второго рода ∫г(a, dr) наз-ся интеграл первого рода ∫г(a,r)ds.
Этот интеграл можно переписать в виде: ∫P(x,y,z)dx + Q(x,y,z)dy + R(x,y,z)dz. Выведем формулу: простая параметризация:
= +- ∫(P(x(t), y(t), z(t))*x'(t) + Q(-//-)*y'(t) + R(-//-)*z'(t))dt на [a, b]
+ если с возрастанием t точка движется по кривой в нужном направлении, - если в противоположном.
** LEARNED 12) Несобственный интеграл функции одного действительного переменного. Критерий Коши и признаки для знакопостоянных и знакопеременных функций
***  Несобственный интеграл
f: [a,b(мб ∞))->R, и интегрируема по Риману на любом отрезке [a, b'], где a < b' < b. Тогда если ∃ конечный lim∫(a,b')fdx при b'->b-0
то тогда эта штука называется несобственным интегралом на [a,b), а f наз-ся несобственно интегрируемой там же.
*** (Формула Ньютона-Лейбница) ∫f на [a,b) = F(b-0)-F(a)
Сходимость интеграла равносильна конечности предела, в случае его наличия оба предела конечны и равны
*** (Критерий Коши) пусть f - интегрируема по Риману на ∀[a, b'] где a<b'<b. Тогда ∫[a,b)fdx сходится <=> ∀e>0 ∃δ>0
что ∀ b' и b'' из δ-окр(b) |∫(b', b'')fdx|<e. 
Рассмотрим F(x) = ∫(a,x)f(t)dt. Интеграл сходится limF(x)<∞ при x->b-0 => это обычный критерий Коши существования предела в b.
*** (Безымянная теорема) f -//- и f ⩾ 0 на нек. U(b-0). Тогда интеграл сх <=> F(x) = ∫[a,x)f(t)dt - огр на [a,b).
НУО можно сказать, что f⩾ 0 везде, ибо при анализе сх. мы можем переставить нижний предел в часть, где она точно положительна - 
нас интересует только верхний предел. Но тогда F(x) - возр(мб нестрого) => по теореме о пределе монотонной функции ограниченность
f равносильна наличию конечного предела F к b-0, то есть сх. ∫f.
*** (Признак сравнения)f,g ⩾ 0 если f = O(g), то сходимость первого влечет сходимость второго, расходимость второго - расх. первого.
Как и в прошлом, считаем, что 0 ⩽ f ⩽ g на всем [a,b). Тогда сх-ть интеграла по g равносильно огр-ти G(x) из предыдущей леммы.
Но т.к. 0 ⩽ ∫f ⩽ ∫g на любом подотрезке, то F - огр => ∫f - сх.
Еще в довесок. Если f ~ g на [a,b), то они сх и расх. одновременно. - следует из предыдущей леммы, ибо f~g <=> f=O(g) ∩ g=O(f)
*** (Признак Дирихле)
f - непр и имеет огр. первообр на [a,b), g - непр. дифф и монотонно -> 0 => ∫[a,b)f*gdx - сх.
Рассмотрим интеграл на [b', b''] a ⩽ b'< b'' < b Проинтегрируем по частям, вынесем F как M - мажоранта (огр). Останется ∫ =
= 2*M*g(b') -> 0 => расписываем определение предела по Коши для 2*M*g(b') => получаем критерий Коши для сходимости интеграла.
*** (Признак Абеля)
f - непр и ∫[a,b) - сх. g - непр. дифф, огр и g' не меняет знака => ∫[a,b)f*gdx - сх.
Пусть g - убывает (иначе возьмем -g и припишем - к ответу). g - монотонна и огр на [a,b) => ∃ кон. limg(x) = C при x->b-0.
Рассм g1(x) = g(x)-C - монотонно стремится к 0. F имеет огр первообразную по безымянной теореме выше => Мы в условиях Дирихле
*** QUESTION (Тригонометрический признак) 
** LEARNED 13) Числовые ряды, критерий Коши, признаки сходимости для знакопостоянных и знакопеременных рядов.
*** Частичные суммы, остаток ряда - все как обычно
*** (НУ сходимости ряда) ∑un - cх => limun->0
Следует из того, что un = Sn+1-Sn => предельный переход.
*** (Критерий Коши) ∑un - сх <=> ∀e>0 ∃N, ∀p ∈N |∑(N, N+p)un|<e
Следует из критерия Коши для наличия предела последовательности. 
*** (Безымянная Т) Сумма модулей сходится => ряд сходится.
Банально потому, что сумма модулей больше.
*** Ряд с какого-то места положителен => сходимость ряда равносильна ограниченности частичных сумм
До положительного куска - роли не играет. После - частичные суммы возрастают => ограниченность ряда сумм эквивалентна наличию
предела (по т. Вейерштрасса) => эквивалентна сходимости суммы в пределе на ∞.
*** Если un = O(vn) на ∞, то ∑un-cx -> ∑vn - cx. расх - наоборот.
НУО: 0 ⩽ vn ⩽ С*un далее очевидно
*** (Интегральный признак сравнения) f - неотр и монотонна на [a,+∞) => ∫[a, +∞) - сх <=> ∑[a, +∞] - cх
если возр, то либо f==0 -сх, либо limf=С расх, либо limf = ∞ - расх
если уб, то либо limf = C - расх, либо limf = 0 - содержательный случай

// Здесь должна быть та самая картинка с графиком и столбиками с твоего второго семака
Очевидно, что функция зажата между "нижними" и "верхними" ступеньками - т.е. между суммами "по левому" и "по правому" краю
ступенек.  Если ∫f - сх, то ∑ нижних ступенек сх, => можно делать предельный переход - сумма сх.
Если ∑ - сх, то ч. суммы сх => ∫[a, N) - огр ∀N => предельный переход по N.
*** (Признак Даламбера) un ⩾ 0: если НСНМ u(n+1)/un ⩽ q < 1 - cх, ⩾ 1 - расх. Предельный: lim(u(n+1)/un) < 1 - сх, ⩾ - расх.
Обычный: 
1) q<1: то u(n+1) <= q*un <= q^2*u(n-1) => un ⩽ u1*q^(n-1) => ∑q^(n+1) - сх => ∑un -> сх // посмотреть у Даши
2) q>=1 - посл НСНМ возр => не выполн НУ сходимости
Предельный:
1) Возьмем q' ∈ (q, 1) НСН n0 ∀n>n u(n+1)/un < q' - работает предыдущая теорема
2) НСНМ u(n+1)/un > 1+e => работает предыдущая теорема
*** (Признак Коши) un ⩾ 0: НСНМ n√un <= q < 1 - сх, >= 1 - расх. Предельный - аналогично.
1) un ⩽ q^n => сходится ибо ∑q^n - сх
2) возр - не вып НУ сходимости
Предельный - как в Даламбере
*** (Признак Абеля для знакопеременных)an, bn: ∑a - cх, bn - монотонна и огр, тогда ∑ab - сх.
Аналонично Абелю для интегралов (заменяем на b1-C и сводим к Дерихле)
*** (Признак Дерихле для знакопеременных)an, bn:  Sn(a) - огр, Sn(b) - монотонно -> 0. Тогда ∑ab - сх.
Аналогично Дерихле для несобственных интегралов, только вместо интегрирования по частям - преобразование сумм Абеля. // Выучить это говно
*** (Признак Лейбница для знакопеременых) bn ⩾ 0 - монотонно -> 0 => bn*(-1)^n - сх.
Рассмотрим "суммы через одно": S_2n - убывает, S_(2n+1) - возр. Пусть они имеют пределы α и β соответственно. Они не ∞, ибо они 
разных знаков (иначе бы bn не -> 0)
Т.к. их разность -> 0, то α=β. 
А дальше какая-то простая химия на стр. 200, которую я не понял => Sn -> a.
** LEARNING 14) Функциональные последовательности и ряды, признак Коши и т. Вейерштрасса равномерной сходимости на множестве
*** Поточечная сходимость ф.п: ∀x ∃limfn(x) = f(x)
Для любого x существует е-корридорчик, что начиная с какого-то N |fn-f| < e
*** Равномерная сходимость ф.п: ∀e>0 ∃n0, ∀n>n0 ∀x |fn(x)-f(x)|<e
Для любого e-корридорчика начиная с какого-то N все функции окажутся в нем
*** (Критерий Коши р.сх.ф.п) fn ⥤ f <=> ∀e>0 ∃n0 ∀n,m>n0 ∀x |fn(x)-fm(x)|<e // эдакая фундаментальность для ф.п.
=> стандартный ход: НСНМ |fn-f|<e/2 и |fm-f|<e/2 => оценим разность сверху суммой => то, что надо.
<= исходя из данного есть поточечная сх => limfm -> f при m -> ∞.
Перепишем то, что дано и устремим m к ∞. Получится ровно определение равномерной сходимости.
*** (Перенос непр) Пусть fn ⥤ f, все fn - непр на E => f - непр на E.
Док-во есть, но я забил. //Восстановить
*** Функциональный ряд (ф.р) ∑un(x) - равномерно сх. на мн-ве E, если посл-ть его частичных сумм Sn равномерно сходится на E.
*** (Критерий Коши р.сх.ф.р) ∑un(x) - р.сх на E <=> ∀e>0 ∃n0, ∀n,m>n- ∀x |∑(i=n..m)un(x)|<e.
Доказано, ибо это КК для р.сх.ф.р. относительно Sn(x) - ф.п.
*** (НУ р.сх.ф.р) ∑un(x) - р.сх. на E => un(x) ⥤ 0 на E
Т.к. Sn-1(x) и Sn(x) ⥤ S, и при этом un(x) - их разность, то отнять одно от другого и получим то, что надо.
*** (Критерий Вейерштрасса -Д У р.сх.ф.р) un(x) по модулю ∀x ∀n мажорируется сходящимся числовым рядом => un(x) - р.сх. на E.
Выпишем критерий Коши сходимости числового ряда, возьмем оттуда ∑(i=n..m)a. Оно мажорирует такую же сумму un(x) при всех х =>
получили КК р.сх. ф.р.
** QUESTION 15) Степенные ряды, теоремы Абеля и ряд Тейлора для ф-ции одного действительного переменного
*** Степенной ряд - ф.р: ∑(n=0..∞)an(z-z0)^n
*** (Первая т.Абеля)  если ст.р. сх при z1 ≠ z0, то ∀z2: |z2-z0|<=|z1-z0| ряд абс. сх в z2.
Ряд сходится => ряд -> 0 при n->0 (НУ сх.ф.р). 
Домножим и разделим ряд в т. z2 на |z1-z0|^n, вынесем дробь из z, она = o(q^n) где q = |z2-z0|/|z1-z0| < 1. Итого ряд сх. по
признаку сравнения
*** Радиус сх. R степенного ряда  - ∀z: |z-z0|<R - ряд cх, ∀z: |z-z0|>R - ряд расх. 
*** (Вторая т.Абеля) ряд сх в z1 => ряд равномерно сх. на отрезке [z0,z1]
Естесственно, что z1 или внутри или на границе круга, я не знаю почему это поясняют в условии. Но да ладно.
Параметризуем отрезок как z = z0 +t(z1-z0), t∈[0,1]. Домножим и разделим ряд на |z1-z0|^n, подставим вместо z параметризацию,
посокращаем, получим ∑an(z1-z0)^n*t^n. Ряд без t^n - сходится, ибо z1 - константа в круге,а t^n - монотонен и огр (константа
при t=0 или 1 и -> 0 при всем остальном.) По признаку Абеля для рядов оно равномерно сх на t∈[0,1] => на z∈[z0,z1].
*** Тейлор - протрахан (я не знаю что именно от меня хотят)
** SMALLQ 16) Матрицы, определитель и ранг матрицы, теоремы о базисном миноре и о ранге матрицы. 
*** Полезные утверждения относительно матриц
**** Любую невырожденную матрицу можно разложить на произведение элементарных матриц
*** Полезные утверждения относительно определителя
**** Определение
det - функция, заданная на множестве квадратных матриц такая, что
1) Для любой строки функция является линейным однородным многочленом от ячеек этой строки
2) det вырожденной матрицы = 0
3) det единичной матрицы = 1
**** Единственность: если d1 - det и d2 - det, то d1 = d2 на любой матице
Доказательство основывается на первом пункте - линейности по строке. Исходя из того, что любую невырожденную матрицу можно 
развалить в произведение элементарных матриц, а det(SA) = det(S)*det(A), то d1(A) = d1(s1)*d2(s2).. и d2(A)=d2(s1)*d2(s2)...
Итого, если функции на одинаковых аргументах дают одинаковые значения, то мы их не различаем.
**** Формула полного разложе;ния
det|A| = сумма по всем перестановкам (j1....jn) a(1,j1),a(2,j2)...an(jn)*(-1)^N(j1, ....jn) где N(...) - число инверсий, которые
нужно сделать для возвращения перестановки в исходный вид (суммарное число нарушений порядка по беку)
Док-во - по индукции. База - детерминант матрицы 2*2 мы знаем
Переход: дано разложение по строке(см ниже), и для каждого минора детерминант считается коррректно по предположению. Заметим,
что все элементы миноров отличны от a1k (ибо мы вычеркивали k строку, когда считали). Домножим на этот элемент и на (-1)^(k+1).
Заметим, что (-1)^N(j1....jn-1)+K+1 = (-1)^N(j1...jn-1)+k-1 (та же четность) = (-1)^N(k, j1....kn-1) - ибо до к стояло ровно (k-1)
чисел его меньших. А теперь навесим сумму по к и получим то, что надо.
**** Формула разложения детерминанта по строке/столбцу: detA = ∑(-1)^(k+1)*a(1k)*d(1k)
Где d(1k) - детерминант подматрицы, полученной вычеркиванием 1 строки и k столбца  
*** Полезные утверждения относительно рангов
**** Ранг произведения не превосходит рангов сомножителей
Пусть определена матрица АВ. Составим матрицу D из всех столбцов A и AB. Т.к. AB - подмножество D, то rgAB<rgD. Но мы можем 
выразить AB через ЛК столбцов А, а потом занулить элементарными преобразованиями. Т.к. добавление нулевых столбцов ранга
не меняет, то rgD ⩽ rgA => rbAB ⩽ rgA. То же самое проворачиваем с B и готово.
*** SMALLQ Лемма2: система из r строк ЛНЗ <=> ∃ невырожденная подматрица порядка R
По индукции: база верна (1 строка - ненулевая => лнз => ∃ ненулевой эл-т - матрица пор-ка 1)
Переход: пусть в системе из r-1 лнз строк есть невырожденная подматрица порядка r-1. Нам дали еще одну лнз строку ->
выразим ее (r-1) подстроку, стоящую под невырожденной матрицей, как ЛК строк этой матрицы (мы могем по лемме(?)). Получим набор коэф.
После этого отнимем от r-той строки эти строки с соотв. коэффициентами. Первые r-1 эл-тов строки занулятся, но какой-то из
последующих не занулится (ибо строка лнз). Перенесем соотв столбик поближе к r-1 матрице. Докажем, что полученная r-матрица 
- невырождена. В самом деле, пусть лнз => есть коэффиценты для столбцов такие, чтоб сумма была 0. Тогда в последней строке
a1*0+a2*0 + ... + a(r-1)*0 + aj*b. Т.к. b ≠ 0 => A =0 и остальные в сумме 0 => противоречие, ибо это лнз-подматрица порядка r-1.
*** Базисная матрица - наибольшая невырожденная квадратная подматрица
    базисные строки и столбцы матрицы - строки и столбцы, на пересечении которых находится базисная матрица
*** (Теорема о ранге) Ранг любой матрицы равен ее строчному рангу и ее столбцовому рангу
Прямо следует из леммы2: строчный ранг r => есть невыр r-подматрица, а все большие - выр => столбцовый ранг = r.
*** (Теорема о базисном миноре) Любой столбец представим ЛК базисных столбцов
Если столбец - базисный, то он представим: все коэффиценты кроме него = 0, а он сам - 1.
Если столбец - не базисный, то по т. о ранге матрицы любые r+1 столбцов - ЛЗ, причем коэффицент при выражаемом столбце точно не 0
(иначе остальные столбцы были бы лз) => разделим все на его коэффицент => выразили
** LEARNED 17) Система линейных уравнений, теорема Кронекера-Капелли
*** Решение СЛУ - совокупность коэффицентов, с которыми столбец свободных членов раскладывается по столбикам системы.
*** Если столбики лнз - то решения или нет, или оно одно (из единственности разложения чего-либо по лнз набору)
*** Элементарные операции не меняют кол-ва решений системы 
ибо эквивалентны элементарным преобразованиям (сложению и домножению на число) исходной СЛУ.
*** Если det матрицы СЛУ отличен от нуля, то система имеет решение, причем только одно
Из единственности разложения столбика свободных членов по столбикам невырожденной матрицы
*** (Правило Крамера) Метод поиска решений: xi = Δi/detAi, где Δi det(A: i replace b)
Пусть x1...xn - решение. Тогда b = a1*x1 + ... + an*xn. Подставим это в Δi, раскроем сумму по линейности det и вынесем xi наружу.
Сократится все, кроме множителя с xi - выражаем его и получаем то, что надо.
*** LEARNED (Кронекер-Капелли) СЛУ совместна <=> ранг матрицы равен рангу расширенной матрицы
=> b - ЛK столбцов матрицы А, соответственно, ранга не повышает
<= Если RgA* = RgA, то мы можем элементарными преобразованиями превратить матрицу A* в матрицу A0 = A+(0). Но у A0 и A 
ранг один и тот же, а rgA0 = rgA* ибо элементарные преобразования ранга не меняют.
*** QUESTION (Т Фредгольма) - почитать где-нибудь еще.
*** (Фундаментальная матрица) - макс. ЛНЗ матрица, в которой каждый столбец - решение соотв. однородной СЛУ.
**** Тогда ∀c x = x0 + Fc - решение неоднородной СЛУ, где x0 - некоторое решение неоднородной СЛУ, а F - ФМ приведенной матрицы
** LEARNED 18) Конечномерные линейные пространства, матрица перехода к другому базису
*** Определение линейного пространства
    Мн-во L наз-ся линейным пространством (л.п.), в его элементы - векторами, если определено и работает следующее:
1) Операция + (замк на L) - симметричная, дистрибьютивная, сущ. единичного элемента по сложению, сущ. обратного элемента
2) Операция * на число (замк на L) - дистрибьютивна по сложению, скобки можно двигать (хз как наз-ся), сущ. ед эл-та по умнож-ю
*** Система векторов - ЛНЗ, если нулевой вектор раскладывается единственным - тривиальным - образом
*** Имплементятся все утверждения из матриц на стр 160
*** Базис B в л.п. L - упор. кон. система в-ров такая, что она ЛНЗ и любой вектор из L раскладывается в ЛК в-ров B
*** Координатный столбец суммы равен суммы их коорд столбцов, коорд. столбец произведения в-ра на число равен число*коорд столбец
В силу линейности всех операций
*** Векторы ЛНЗ <=> коорд. столбцы ЛНЗ
Из того, что координатный столбец ЛК есть ЛК координатных столбцов.
*** Все базисы одного размера
Просто из того, что если в одном больше, чем в другом, то часть другого выражается как лк через первый - противоречие
*** Размерность пространства := размерность ее базиса. Обозначение dimL
*** Бесконечномерное пространства базиса не имеет. Пример - пространство функций, непрерывных на отрезке. (∀m ∃ЛНЗ 1,t,t^2...t^m)
*** (Замена базиса) Разложим один базис по другому: матрица коэффицентов := матрица перехода к новому базису
Можно переходить последовательно: e'' = e'S, e' = eT => e'' = eST - записываются справа
Любая S: detS ≠ 0 является матрицей перехода к какому-то базису, ибо столбцы S - ЛНЗ => являются координатами соотв. системы ЛНЗ 
векторов, которые есть новый базис
Координаты вектора в старом базисе * матрицу перехода есть координаты вектора в новом базисе
*** Ориентация пространства
Зафиксируем e0. Тогда ∀e - базиса такого, что e = e0S, detS > 0 - класс базисов S+, <0 - класс базисов S-. 
Вещественное ЛП называется ориентированным если из двух классов базисов выбран один. Задать ориентацию ЛП можно выбрав один базис
и считать его положительно ориентированным
** LEARNED Подпространства
*** Набор векторов сам по себе замкнутый относительно сложения и умножения на число - линейное подпространство
*** Линейная оболочка - подвид линейного подпространства
И правда, сумма двух ЛК есть ЛК, ЛК умноженное на число есть ЛК.
*** ЛНЗ система векторов из ЛО - базис ЛО
*** Сумма подпространств - ЛО объединения их векторов, пересечение подпространств - ЛО пересечения их векторов.
*** SMALLQ Прямая сумма подпространств := размерность суммы равна сумме размерностей
** SMALLQ 19) Линейные отображения конечномерных линейных пространств, матрица линейного отображения
*** Линейное отображение A: L->L' такое, что ∀x,y ∈ A, a∈R. A(x + y) = Ax+Ay, A(a*x) = a*Ax
Линейное преобразование: линейное отображение при L = L'
*** При лин. отобр. подпространство переходит в подпространство, причем не большей размерности.
Пусть у нас есть подпр. L2 ∈ L, (e1,...,ek) - базис L2, тогда ∀x∈L2 x = a1*e1+...+ak*ek. Тогда A(x) = a1*A(e1)+ .. + ak*A(ek)
То есть, любой A(x) - ЛК в-ров A(e), т.е. принадлежит их ЛО => подпространство
*** rgA := Размерность множества образов всех в-ров из L, т.е. размерность A(L).
*** Если dimL = rgA, то A(L) совпадает с L', т.е. каждый в-р из L' имеет прообраз в L := отображение сюръективно. 
*** Мн-во X ⊂ L таких, что A(x∈X)=0 - ядро A := kerA. X - подпространство L:
Если ядро - это только 0-вектор, то понятно. Если A(x)=0 и A(y)=0, то A(αx+βy) = αA(x)+βA(y) = 0 => не вышли за A(X) => подпр-во.
*** Разным векторам - разные образы := инъективное отображение
*** Т. отображение инъективно <=> kerA=0
=> при ker ≠ 0 одному вектору соответствует сколько угодно прообразов: например, его "официальный" образ и куча векторов из ядра
При отображении они все занулятся => не инъективно.
<= тоже можно легко доказать от противного
*** Инъективно => лнз вектора переходят в лнз вектора: 
от противного: A(x1)+...+A(xk) = 0 - лз  => A(x1+...+xk)=0 => x1..xk = 0 - т.к. инъективно => лз
*** Матрица линейного отображения A в паре базисов e, f := матрица, столбцы которой - коорд. столб. в-ров A(e1),A(e2)... в f
*** Ранг матрицы лин. отоб совпадает с рангом самого отображения. 
Образы векторов, которые отвечают базисным столбцам матрицы А - ЛНЗ => образуют базис => любой вектор раскладывается по этому 
базису (и его координаты - лк координат базисных векторов) => размерность пространства и матрицы одна и та же.
*** QUESTION rgA + dim(kerA) = rgL 
// я был сонный :( допонять
*** Отображение биективно <=> dimL(=n) = dimL'(=m) = rgA
следует из того, что для инъекции необходимо rgA=n, а для сюръекции rgA=m.
** LEARNED 20) Линейные преобразования конечномерного линейного пространства. Собственные числа и собственные векторы лин. пространства.
*** Линейное преобразование:= A: L->L
*** Матрица лин. преобр := коорд. представление в-ров базиса e, записанное в по столбикам
*** Перенос матрицы л.пр. А в другой базис: A'=S^(-1)*A*S, где S - матрица перехода от нового базиса к старому. 
*** Для преобразований определено произв: AB. Если AB=BA => A и B - перестановочные
Так, например, определим степень A^k := AA^(k-1). Рассмотрим преобразование B, полученное как ЛК A разных степеней:
B = a1^A+a2*A^2 + ... + ak*A^k. Нетрудно проверить, что любые B1 и B2 перестановочны с А и сами с собой.
*** Инвариантное относительно А подпространство - все образы лежат в том же пространстве
Нулевое подпр. и все подпр. - инвариантны относительно любых А
Если, например, у нас есть отображение-поворот вокруг оси, то все вектора, параллельные этой оси, будут переходить сами в себя
и не выйдут за подпространство "ось". => ось - инвариантное.
*** Теорема "о нулях вне инвариантного подпр-ва"
Пусть есть подпр-во L'∈L - инвариантна по А, и |A| - матрица л.преобр. dimL'=k, dimL=m. Возьмем такой базис, что первые k векторов
лежат в L'. Тогда в матрице А внизу первых k столбиков (после k-ой строки) будут одни нули.
Действительно, т.к. все вектора из L', в том числе и e1..ek, переходят в L'. Соответственно (n-k) последних координат будут 
нулевые, ибо эти вектора не представлены в L\L'.
*** Если преобразования перестановочны, то kerA и imA инвариантны относительно B и наоборот
1) x ∈ kerA => A(x) = 0 => B(A(x)) = 0 = A(B(x)) => B(x) ∈ kerA
2) x ∈ imA => ∃z: x = A(z) =>B(x) = B(A(z)) = A(B(z)) => B(x) ∈ ImA
*** Зачем нужны собственные значения и собственные вектора
У нас есть задача поиска подпространства, инвариантного отностиельно заданного преобразования А.
Мы знаем по предыдущей лемме, что если А и B - перестановочны, то А инвариантно относительно ядра B.
Тогда давайте соберем на коленке B и найдем его ядро - это и будет искомое подпространство.
B должно быть перестановочно с А. Мы знаем, что таким свойством обладают полиномы от А. Давайте возьмем самый простой из них:
B = A-λE. Теперь ищем при каких λ эта штука имеет ненулевое ядро. Полученные λ назовем собственными числами А, а соответствующие
ему ядра B - собственными подпространствами А, как подпространства, которые инвариантны относительно А.
Далее, найдем сами эти пространства. Для этого для каждого λ нужно решить систему вида (A-λE)x = 0 - однородная система л.у.
Любое ее решение можно записать как ЛК векторов из ФСР, которые и будут базисом собственного подпространства, соответствующего λ.
И, наконец, собственные вектора - это ненулевые вектора собственных подпространств. Выжимка:
*** Собственное значение := такое λ, что подпр-во ker(A-λE) - ненулевое. Собственное подпр-во для λ := это самое подпространство
*** Собственный вектор для λ := такой x ≠ 0, что Ax = λx. 
Это значит, что собственный вектор - это ненулевой вектор собственного подпространства.  
*** Характеристическое ур-е: ядро отлично от нуля <=> det(A-λE) = 0
Потому что сумма ранга матрицы и размерности ядра равна размерности отображаемого пространства: ядро не нуль - ранг матрицы
меньше ее размера => лз => det = 0.
** LEARNED 21) Билинейные формы в конечномерном линейном пространстве, теорема о приведении билинейной формы к каноническому виду
*** Билинейные функции или билинейные формы - функция от двух аргументов, линейная по каждому из них.
*** Матрица билинейной формы - матрица значений формы на всех комбинациях базисных коэффицентов
*** Симметричная билинейная форма: B(x,y) = B(y,x) для любой пары векторов
У нее еще матрица тогда симметрична, это несложно доказывается
*** Квадратичная форма k(x) = B(x,x), где B - билинейная симметричная форма.
*** Для каждой квадратичной k(x) соотв. B(x, x) задается единственным образом. 
Подставляем x+y, разваливаем B по линейности, потом замечаем, что B(x,y)=B(y,x) и выражаем B(x,y) через k
*** Матрица квадратичной формы - матрица соответствующей билинейной формы.
*** Для каждой квадратичной формы существует базис, в котором ее матрица имеет диагональный вид
Это, скорее, алгоритм, а не теорема.
Начинаем с первой стоки. 
a) Если a11 ≠ 0, то сначала занулим этим элементом (элементарная операция домножения на a1j/a11 и отнятие)
всю первую колонку кроме a11, потом этим же элементом и элементарными операциями столбцов занулим всю первую стоку кроме a11.
b) Если a11 = 0, то ищем ненулевой a1i. Если он есть, причем aii ненулевой, то мы переставляем i строку и i столбец на 1 место
элементарными операциями свайпа строк
Если же ненулевого элемента нет, то вся строка нулевая, и оно и так уже частично в диагональной форме. 

И так для всей матрицы. В результате получится диагональная.
При этом, на каждом шаге у нас (в силу того, что матрица симметрична) производились одинаковые действия как для сток, так и для
столбцов. Объединим все элементарные операции со строками в S, тогда к столбцам были применены S^T. По формуле для перехода к новому
базису, получившуюся диагональную B' можно выразить, как S^T*B*S. 
Таким образом B' - матрица квадратичной формы в каком-то базисе, который задается матрицей перехода S. Доказали.
*** Для каждой квадратичной формы существует базис, в котором она имеет канонический вид (0, -1 или 1 на диагинали)
Пляшем от уже имеющего диагонального вида матрицы. Он соответствует какому-то базису. Разделим каждую i строку и i столбец на
модуль того, что стоит на его пересечении. Это равносильно делению соответствующего базиснуго вектора на число. Получили 
каноничную форму и соответствующий базис. 
** Линейные функции
*** Линейная функция на L := f:L->R(C) такая, что f(ax+by) = af(x)*bf(y)
*** Пространство L* линейных функций на L - линейное пространство
Здесь Бек помахал руками в духе "пространство функций изоморфно пространству строк длины n, а для строк работают аксиомы линейного
пространства, значит и для функций работают". Матлог какой-то. Спросить у Алины.
*** Любая линейная функция на базисе e задается полиномом f(x)=ф1*а1+ф2*а2+...+фn*an, где a - коорд. x, фi = f(ei).
распишем x как линейную комбинацию векторов базиса, подставим это в функцию, повыносим все в силу линейности, получим то, что надо
При этом ф называются коэффицентами функции в базисе e.
*** Биортогональный базису e базис - базис в L* такой (p1...pn), что pi(x) := i-ая коорд. x => pi(ei)=1, pi(ej)=0.
Если расписать эти функции в виде их коэффицентов и составить столбиками в матрицу, то получится E. Очевидно, оно лнз. А так как
пространство L* тоже размерности n, то это - базис.
** QUESTION 22) Конечномерные Евклидовы линейные пространства, теорема об ортогональном дополнении, процесс ортогонализации Грамма-Шмидта
*** Евклидово пространство - линейное пространство с определенным скалярным произведением: 
свойства: симметричность, линейность по первому аргументу, положительность для (x,x).
оно же - положительно-определенная квадратичная форма, ибо эти аксиомы совпадают с аксиомами и св-вами билинейной симметричной формы
*** |x| = √(x,x) - длина, cosф = (x,y)/(|x|*|y|)
*** неравенство треугольника: |x+y| <= |x| + |y|
расписываем (x+y, x+y) по линейности, получаем <= (|x|+|y|)^2
*** Матрица Грамма для базиса e: матрица попарных скалярных произведений базисных векторов. detМГ любого базиса > 0:
это следует из критерия Сильвестра: матрица симметрична => все ее главные миноры положительны (в том числе и тот, который
вся матрица)
*** (т. о матрице скалярных произведений) x1...xk - набор векторов. det "матрицы Грамма" для него > 0 если x - ЛНЗ, и = 0, если ЛЗ
ЛНЗ => базис => по предыдущей теореме
ЛЗ => значит a1*x1 + ... + a1*xk = 0. Умножим скалярно это на каждый из векторов, получим
a1*(x1,x1) + .... + ak(x1,xk) = 0
...
a1*(xk,x1) + .... + ak(xk,xk) = 0
Системе по-прежнему удовлетворяют коэффиценты a => матрица имеет ненулевое решение => det=0.
*** Ортонормированный базис := базис, в котором основная квадратичная форма (оно же скалярное произв.) имеет канон. форму
Вестимо, что матрица Грамма для ортонормированного базиса единичная => векторы базиса попарно ортогональны и || = 1.
*** Ортогональная матрица: S^T*S = E. Только такая матрица может быть матрицей перехода м\у двумя ортонормированными базисами
Из определения: S^T = S^-1. => S*S^T=E => S^T - тоже ортогональная.
*** Ортогональное дополнение
Пусть E' - k-мерное подпространство n-мерного Евклидового пространства. Тогда ортогональное дополнение E! к нему - мн-во всех 
векторов, ортогональных каждому вектору из E'.
*** QUESTION (об орт доп) Ортогональное дополнение k-мерного подпространства есть n-k-мерное подпространство.
Вектор лежит там тогда и только тогда, когда (x,a
//доразобраться
*** E - прямая сумма любого подпространства и его ортогонального дополнения
Очевидно следует из того, что общих ненулевых векторов у них нет, и сумма размерностей равна n.
*** QUESTION Ортогональная проекция x∈E на E' := x' такой, что x = x' + x'', x''∈ E!. 
*** Метод ортогонализации Грамма-Шмидта
Все основывается на формуле взятия проекции на вектор: xi = ((x, ei)/|ei|^2)*ei
Пусть у нас дан неортогональный базис f1...fn. Мы его хотим ортогонализировать. Запускаем процесс:
1. h1 = f1
2. h2 = f2 - (f2, h1)/|h1|^2*h1 (вычеркнем из f2 все компоненты h1 => h2 перп. h1
....
k: hk = fk - ∑(fk, hi)/|hi|^2*hi (i = 1..k-1) (оставим в новом векторе только перпендикулярные компоненты)
На каждом шаге новый вектор будет перпендикулярен всем предыдущим, ибо будет в проекции на них давать 0 (мы вычеркнули все проекции)
На k шаге у нас hk раскладывается в f1...fk (по индукции: 1 раскл, а на k шаге раскл с коэф при fk = 1, а сумма раскладывается по
индукционному предположению). Отсюда же следует, что hk ≠ 0, иначе бы f1...fk были бы ЛНЗ. => итого, мы построили ненулевой набор
n взаимно-перпендикулярных векторов - базис Евклидового пространства.
Теперь еще можно поортонормализировать его, разделив каждый векторок на свой модуль.

Рассмотрим так же матрицу перехода от f к h. Т.к. коэффицент при fi в разложении hi по f1..fi будет единичка (а остальные f в
разложении не участвуют) то матрица перехода будет верхнетреугольная, с единичками на главной диагонали.
** QUESTION 23) Линейное преобразование Евклидового пространства и его сопряженное преобразование. Ортогональные преобразования конечномерных Евклидовых пространств
*** Сопряженное A линейное преобразование A* := такое, что ∀x,y (Ax, y) = (x, A*(y))
Найдем как связаны матрицы A и A*
Для этого пусть a,b - координатные стобцы x и y, а A и A* - соотв матрицы отображений:
(Aa)^T*Г*b = a^T*Г*A**b, где Г - матрица Грамма для данного базиса.
оттранспонируем, вычеркнем координаты a и b, и получим A^T*Г = Г*A*.
А если же у нас пространство ортонормированное (Г - единичная матрица), то A^T=A*.
*** Каждое л.преобр имеет единственное сопряженное преобразование.
Очевидно, ибо выбрали бы базис и два потенциально сопряженных, ортонормировали бы базис, и у них бы совпали матрицы при подстановке
в то, что написано в самом конце предыдущего пункта.
Оттуда же вытекает, что характеристические полиномы совпадают (ибо они совпадают у транспонированной матрицы) => совпадают все 
корни и кратности
*** Ортогональное преобразование: то, что сохраняет скалярное произведение: ∀x,y (Ax, Ay)=(x,y)
То есть изоморфизм пространства самого на себя.
*** QUESTION А - ортогонально <=> A* = A^-1
//ЯННП почему 7 => (x, A*A(y)) = (x,y)
** QUESTION 24) Самосопряженные преобразования. Теорема о собственных числах и собственных векторах самосопряженного преобразования.
*** Самосопряженное преобразование := A* = A
Из этого сразу следует, что его корни вещественны
*** QUESTION Все корни характеристического многочлена собственного преобразования вещественны
// почитать про 
*** Собственные подпространства самосопряженного преобразования попарно ортогональны.
Эквивалентно тому, что собственные вектора, пренадлежащие разным собственным числам попарно ортогональны.
Пусть A(x) = λx и A(y) = μy. (Ax,y) = λ(x,y), (x, Ay) = μ(x,y) => (λ-μ)(x,y) = 0 => x перп y
*** Если подпр-во E' - инвариантно отн A - самосопр, то E! - так же инвариантно относительно A.
x ∈ E', y ∈ E! => (Ax, y) = 0 - дано. Но т.к. A - самосопряженное, то (x, Ay) = 0 => чтд.
*** (осн. т. о самосопр.преобразованиях) A - самосопр. преобр. E => в E есть ОРТН базис, состоящий из собств. в-ров A.
Для этого достаточно доказать, что L - сумма собственных пространств A - совпадает с E. А для этого докажем, что L! - пустое.
Для начала заметим, что L - инвариантно по A (действительно, если x раскладывается по собственным векторам, то и его образ
раскладывается). => L! ортогональное - инвариантно. Предположим, что оно ненулевое.
Рассмотрим ограничение A' для А на L!. Это - самосопряженное преобразование => вещественные собственные числа => имеет хотя бы
один собственный вектор. Но т.к. этот вектор собственный и для А (по св-вам самоспор. преобр), то он лежит в L. => В L! он лежать
не может. Противоречие
** QUESTION 25) Билинейные формы в конечном Евклидовом пространстве. Т. Об одновременном приведении к диагональному виду двух билинейных форм
*** Преобразование, присоединенное к билинейной функции:= такое А, что B(x, y) = (x, Ay)
*** Каждая билинейная функция имеет одно единственное присоединенное преобразование
(x,Ay) = x^T*Г*Ay => билинейная функция с матрицей ГА => A = Г^-1*B. => единственна, ибо задается однозначно
корректность => подставляем назад и получаем то, что надо
Заметим, что для ОРТН базиса связь особенно проста: A=B.
Поэтому для симметричных билинейных функций присоединенное преобразование является вдовесок самосопряженным.
*** В евклидовом пространстве для каждой квадратичной формы имеется ОРТН базис, в котором ее матрица имеет диагональный вид
Очевидно: искомый базис - столбики соответствующего присоединенного самосопряженного преобразонвания (ведь оно базис по какой-то
теореме и имеет диагональный вид)
*** QUESTION Об одновременном приведении к диаг. виду двух форм:
Пусть у нас в линейном (не обязательно евклидовом!) пространстве L заданы две квадратичные формы: k, h, причем h - положительно
определенная. Тогда в L существует базис такой, что обе формы имеют в нем диагональный вид.
// Я малость не понял здесь переходы
Возьмем k как основную квадратичную форму (зададим ею скалярное произведение). ... и т д
* Физика
  Механика
** 1) Материальная точка. Системы отсчета. Радиус-вектор, путь, перемещение. Траектория. Скорость и ускорение. Графики движений. Движение точки по окружности, угловое ускорение. Нормальное и тангенциальное ускорение точки. Радиус кривизны траектории.
*** СО - тело или система тел, относительно которой определяются координаты всех остальных
*** Возьмем x,y,z - расстояния от начала СО до тела, совместим их в тройку (x,y,z) и проведем в эту точку вектор из начала координат.
Это радиус-вектор.
*** Есть два типа СО - правая и левая
*** Мат. точка - тело, размеры которого настолько малы, что при анализе движения этого тела их можно не учитывать.
*** средняя скорость - отношение пройденного пути к промежутку времени
*** истинная или мнгновенная скорость - производная по функции координаты. 
*** ускорение - производная скорости по времени
*** угловая скорость - производная угла по времени, угловое ускорение - произвоная по скорости
u = wr, a = w'r
*** движение по криволинейной траектории описывается так же, только x(t) -> r(t). Производные - векторные, и тд.
вектор скорости направлен по касательной к траектории движения точки
заменим радиус-вектор из точки на соответствующий ему вектор скорости из той же точки. Тогда эти вектора очертят траекторию 
под названием годограф скорости. Вектор ускорения будет направлен по касательной к соответствующему вектору скорости, по аналогию
скорости и радиус-вектора.
*** центростремительное ускорение: a = w^2*r. Направлена в центр.
    u = wr, a = wu=w^2*r - из соображений о том, что можем писать для траектории => можем писать для годографа
*** нормальное ускорение - компонента ускорения, перпендиуклярная направлению движения
    вывести это можно через d(u*s) = s*dv/dt + u*ds/dt = s*dv/dt + u^2/r*n первое - тангенциальное ускорение, второе - нормальное
    тангенциальное меняется только по величине, нормальное - только по направлению
*** тангенциальное ускорение - компонента ускорения, сонаправленная с направлением движения
*** Радиус кривизны траектории - радиус окружности, по которой движется точка в данный момент времени
    **
    **
** 2,4) Законы Ньютона. Инерцальные и неинерциальные системы отсчета. Импульс частицы, системы. ЗСИ.
*** (1) ∃ СО, в которой тело (мат. точка), на которое не оказывают влияние внешние силы, движется равномерно прямолинейно или покоится.
*** Инерциальная система отсчета:такая система, в которой все свободные тела движутся равномерно и прямолинейно.
    пример - земля, система Коперника
*** Масса - мера инертности тела
    Ну или: отношение масс двух матрериальных точек это отношение приращений их скоростей в результате взаимодействия, взятому
    со знаком минус
*** Импульс - мера движения - произведение скорости на массу (векторная вещь)
    импульс системы - векторная сумма импульсов всех тел системы
*** (ЗСИ) Импульс изолированной системы двух материальных точек сохраняется, независимо от взаимодействия между ними
    Является результатом опыта и введенного определения массы
*** Сила - производная импульса по врмени. 
    Зависит от коордитнаты материальной точки и ее скорости
*** (2) производная импульса м.т. по времени равна действующей на нее силе 
    по определению силы
*** (3) силы взаимодействия двух материальных точек равны по величине и противоположны по направлению
    дифференцируем ЗСЭ и получаем то, что надо 
*** силы можно разделить на внутренние и внешние: силы взаимодействия и внешиние силы
*** изменение суммарного импульса системы равно сумме всех внешних сил 
    Для каждой точки системы запишем второй закон Ньютона, разделив сумму внешних и внутренних сил, действующих на эту точку
    сложим почленно для всех точек, внутренние суммы уйдут => получим то, что надо.
*** Импульс силы - произведение постоянной силы на время ее действия, или интеграл силы по времени для переменной силы
** 3) Центр масс системы частиц. Скорость и ускорение центра масс. Теорема о движении центра масс. 
*** Центр масс - точка, куда указывает радиус вектор r = (r1*m1+...+rn*mn)/(m1+...+mn)
*** Скорость и ускорение центра масс получается дифференцируя то, что выше
*** Центр системы движется как м.т. с м = ∑mi, а сила - геометрическая сумма всех внешних сил, действующих на систему
диффренцируем ур-е для ц.м, переносим массу. Слева - суммарный импульс системы. А производная по нему равна сумме всех вн. сил (п2-4)
** 5) Уравнение Мещерского, формула Циолковского
*** Мещерского: m(dv/dt) = Vг*(dm/dt) + F, где Vг - относительная скорость газов, F - сумма внешних сил
Записываем разность импульсов системы в момены времени t и dt, приравниваем к импульсу внешних сил за dt:
(m-dm)(u+dv)-mv+Vг*dm = F*dt
сокращаем все и приводим к виду выше
*** Циолковского: m0/m = e^(v/Vг), при F = 0
Берем Мещерского, зануляем F, переносим в одну сторону dm/m, в другую - все остальное. Навешиваем интеграл, интегрируем.
После этого ищем константу из начальных условий: v = 0 при m = m0. Подставляем, получаем то, что надо.
** 6) Работа силы, мощность, теорема о кин. энергии частицы, теорема Кёнига.
*** Работа силы F на перемещении ds наз-ся произведение проекции силы на вектор перемешения на величину самого 
dA = F*ds*cosα. = (F, ds). - элементарная работа на ds, на котором F постоянна.
A = ∫(по l) (F, ds) -работа силы вдоль кривой l.
*** Мощность - работа в единицу времени
P = dA/dt
*** (т. о кинетической энергии) Работа силы равна приращению кинетической энергии частицы 
в интеграле для А сделаем замену: F = dp/dt, ds = vdt, получим A = ∫(dp,v). dp = mdv => = ∫m(v,dv). Теперь условимся за u считать 
длину вектора v, тогда u^2 = v^2 по определению. Поинтегрируем, получим vdv=udu => убираем все вектора из интеграла и интегрируем от
v1 до v2. То, что получили := разность кинетических энергий частицы.

Кинетическая энергия в системе зависит и от внутренних сил: шарики, летящие навстречу ускоренно притяжением друг друга.
*** (т.Кёнига) связь м\у кинетическими энергиями частицы в разных СО: K = K' + 1/2*m*V^2, где V - относительная скорость СО.
пусть скорость  S' = V отн S. Тогда для произвольной частицы верно: v = v'+V (где v - в S, v' - в S'). Пихнем в ур.е. Кин Е:
1/2*m*v^2 = 1/2*m*v'/2 + 1/2*m*V (+ m*V*v' = p'*V, где p' - импульс частицы в S'), ну или:

K = K' + 1/2*m*v + V*p'
просуммируем это дело для всех частиц, в итоге m -> масса системы, а p' -> суммарный импульс системы. 
p' можно расписать как m*vc, где m - масса системы, а vc - скорость движения центра масс системы относительно S'. 
Пусть мы выбрали S' так, что центр масс системы относительно нее никуда не двигается, тогда:
K = K' + 1/2*m*V^2

Формулируется это так:
Кинетическая энергия системы равна сумме кинетической энергии движения центра масс и энергии движения всего остального в СО центра масс.

** 7) Консервативные и неконсервативные силы. Потенциальная энергия. Закон сохранения механической энергии.
*** Консервативные силы: такие, работа которых зависит только от начальной и конечной конфигурации системы и не зависит от траектории.
Рассматриваются примеры: гравитация (показать, что работа зависит только от разности высот), центральные силы (которые всегда направ-
лены на или от какой-то точки (кулоновская)) (через радиус-вектора показать, что работа от траектории не зависит:
ds*cos(F, ds) - проекция элементарного перемещения на направление силы => на направление радиус-вектора к точке притяжения => 
ds*cos(F, ds) = dr. => dA = F(r)dr. Интегрируем и получаем то, что надо.
*** Работа консервативных сил по любому замкнутому контуру равна нулю
    Доказывается из того, что интеграл "туда" и "назад" одинаков, просто разного знака.
*** Неконсервативные - все остальные: трения (диссипативные), Лоренца (гироскопические := зависящие от скорости и перпендикулярные движению)
Они часто зависят еще и от относительных скоростей, но их работа всегда 0
*** Потенциальная энергия
Пусть на систему действуют только консервативные и гироскопические силы. Тогда можно ввести понятие потенциальной энергии:
Выберем нулевое положение. Выберем первое. Работа, совершаемая потенциальными силами при перемещении тела из первого положения
в нулевое, называется потенциальной энергией в первом положении.
Потенциальная энергия - функция только от координат. Определена не однозначно, а с точностью до константы.
Работа консервативных сил равна убыли потенциальной энергии системы // в две строчки на 137.
Но работа сил выражается через прирост кинетической энергии => ЗСЭ
*** Полная энергия системы - сумма механической и потенциальной энергии системы.
*** ЗСЭ: в системе с одними только потенциальными и гироскопическими силами полная энергия остается неизменной: 
происходят лишь переходы из кинетической в потеницальную и наоборот. См. *Потенциальная энергия.
** 8) Абсолютно упругий и абсолютно неупругий удар двух частиц. Построение и использование диаграмм скоростей. Система центра масс. Движение системы из двух взаимодействующих частиц (задача двух тел). Приведённая масса. Внутренняя энергия. Общефизический закон сохранения энергии.
*** QUESTION Абсолютно упругий удар
При таком ударе не возникает никаких диссипативных сил, поэтому работают и ЗСИ, и ЗСЭ
//Теория
Кинетическая энергия центра масс - не меняется, так как не меняется его скорость // почему?
Меняется только лишь кинетическая энергия одного шара относительно другого (выразить можно через приведенную массу)
В определенный момент при столкновении в СО 2 шара оба шара будуь покоиться (вся К.отн. перешла в потенциальную упругого сжатия)
потом оно начинает разжиматься и вся энергия переходит назад в кинетическую.
//Практика
пишем ЗСЭ и ЗСИ. Первое - квадратное. Выносим массы (то же самое с ЗСИ), раскрываем как полные квадраты. Так как результат
"скорости не изменились" нас не устраивает, сокращаем массы и разность, остается v1+v1' = v2+v2'. Решаем это и импульс, получаем ответ.

*** Абсолютно неупругий удар
В момент удара ЗСИ продолжает работать, а ЗСЭ - нет. Поэтому новая скорость ищется только из ЗСИ:
m1*v1 + m2*v2 = (m1+m2)*v2.
Потери кинетической энергии считаются из разности энергий "до" и "после", и равны: 1/2*μ(v1-v2)^2, где μ - приведенная масса (m1*m2/(m1+m2))
Итого: потери К при столкновении равны половие приведенной массы * квадрат относительной скорости.

Неупругий удар всегда сопровождается потерей кинетической энергии, например, исходя из т. Кёнига, где К складывается из движения
центра масс и движения вокруг центра масс. Второе при слипании двух шаров - исчезает.

*** QUESTION Задача двух тел, приведенная масса.
Пусть у нас есть два тела, которые взаимодействуют с силой F соответственно. Выпишем 2Н для каждого тела в векторной форме. 
В итоге, получится d^2(r)/dt^2 = F*(1/m1 + 1/m2), где r - радиус-вектор, соединяющий эти два тела. То, что в скобках можно выразить
как 1\μ, где μ = m1*m2/(m1+m2) - приведенная масса. И переписать в итоге два уравнения в одно:
μ*d^2(r)/dt^2 = F. Уравнение дает закон движения второго тела (с массой μ) в поле силы первого, как неподвижной точки.
// здесь же он вводил дополнительно ур-е на систему центра масс (не понял как и зачем).
*** QUESTION Система центра масс: в ней можно рассматривать все удары как центральные
Я не нашел пока где это читать
*** Внутренняя энергия тела: энергия беспорядочного движения атомов и молекул тела, оно же - тепло
*** Общефизический ЗСЭ: энергия не появляется из ниоткуда и не исчезает бесследно.
Одно из наиболее широких обобщений в физике, исключительно опытный факт.
// здесь должно быть много философии и исторических рассказов
Так, например, потеря механической энергии при неупругом столкновении тел - это работа против внутренних сил тел по их деформации. 
Ну, этим принципом еще кучу всяких вещей нашли, типа радиоактивности, нейтрино и так далее.
*** QUESTION Построение и использование диаграмы скоростей
WTF?
** 9) Элементы специальной теории относительности. Принцип относительности. Преобразование Лоренца для координат и времени. Относительность одновременности. Замедление времени. Собственное время жизни частицы. Сокращение длины. Собственная длина. Эффект Доплера. Интервал и его инвариантность.
*** Интервал: S12 := √((c(t1-t2))^2 - (x2-x1)^2 - ... ) инвариант в любой инерциальной системе отсчета.
Для любых двух событий эта величина инвариантна относительно системы отсчета
*** Преобразование Лоренца для координат и времени: x' = γ(x+v*t), y' = y, z'=z, t' = (t + x*v/c^2)*γ
постулируется
*** Лоренцевское сокращение времени: dt' = dt√(1-(v/c)^2)
Эксперимент с часами. Записываем интервалы в первой и второй СО (во второй dx'=dy'=dz'=0), и приравниваем их.
*** Лоренцевское сокращение длины: l = l0*√(1+β^2), где l0 - длина линейки в ее СО, l - длина линейки в нашей со
Эксперимент с часами 2: "меряем длину пробегающего поезда".
Получается, что l/l0 = t/t, а соотношение времен мы знаем.
*** Формула сложения скоростей: V = (V0+V')/(1+V*V0/c^2)
Выводится из преобразования координат и времени: dx'/dt'.
*** Эффект Доплера (продольный): T' = T * √(1+β)/(1-β)
Эксперимент "удаляющаяся ракета": выражаем время, которое прошло от момента посылки до момента приема: tи = T + x/c = v*tи/c
выражаем tи и переходим по Лоренцевскому времени в СО приемника - получаем то, что надо
*** Собственное время := dt' - время в движущейся СО
Собственное время - всегда наименьшее (исходя из лоренцевского сокращения времени)
*** Собственное время жизни частицы: время жизни в ее собственной СО
В нашей СО оно куда больше. Так, например, собственное время жизни мюонов порядка 2мкс. Они рождаются в верхних слоях атмосферы, и, при
этом, мы их можем регистрировать у поверхности. Это именно потому, что "наше" время "длиннее".
*** Релятивистский фактор γ := 1/√(1-β^2), где β = v/c
** 10) Импульс, энергия релятивистской частицы, энергия покоя, кинетическая энергия. Связь между энергией и импульсом частицы. Уравнение движения релятивистской частицы.
*** Релятивистский импульс: γmv
*** Релятивистская энергия: γmv^2
*** Полная энергия релятивистской частицы: E^2 = p^2*c^2 + m^2*c^4
Здесь инвариантом является mc^2, достаточно перенести импульс в другую сторону.
*** Уравнение движения для релятивистских частиц: dP/dt = F, где P - релятивистский импульс
Если продифференцировать, то получается страшная хренотень из двух неколлинеарных слагаемых => в релятивизме сила неколлинеарна
ускорению
*** QUESTION Кинетическая энергия.
dK = d(γmc^2) - приращение кинетической энергии есть приращение полной.
K = γmc^2 - mc^2 = (γ-1)mc^2 = E - mc^2 - кинетическая энергия это полная энергия за вычетом энергии покоя
 получается интегрированием предыдущего 
Доказано в Савельеве "Механика"
*** Взаимосвязь м\у импульсом и энергией: p = E/c^2*v
    из того, что E = γmc^2
** 11) Момент импульса материальной точки относительно точки и относительно оси. Момент силы. Момент импульса системы материальных точек. Уравнение моментов. Закон сохранения момента импульса.
*** Разница между моментом относительно точки и моментом относительно оси
Момент вектора относительно точки сам есть вектор. Момент вектора относительно оси есть проекция на эту ось его момента относительно
точки, лежащей на этой оси.
*** Момент силы относительно точки: M = [r*F], где r - радиус-вектор из .О до точки приложения F - силы. М отложен из точки О.
В силу линейности: F = F1 + F2 => [rF] = [rF1] + [rF2]
*** Момент импульса относительно точки: L = [r*p]
*** Уравнение моментов: dL/dt = ∑M. 
Дифференцируем L из определения, раскрываем как производную произведения. r' = 0, т.к. точка O - неподвижна. А сумма моментов это момент
равнодействующей всех сил, можно воспринимать как суммарный момент.
*** Момент импульса системы отн. нек. начала - век. сумма всех моментов импульсов отн. этого начала.
*** Момент сил, действующих на систему материальных точек, определяется так же.
Можно сначала найти равнодействующую всех сил (или сумму импульсов) а потом уже считать момент
*** Уравнение моментов для системы: dL/dt = ∑M(внеш).
Из третьего закона Ньютона, и второго для системы (парные внутренние силы зануляются)
*** ЗСМИ: если сумма моментов внешних сил = 0, то момент импульса системы сохраняется. 
Прямое следствие из того, что выше.
*** Изменение момента импульса/силы при переходе в другую ось: L = L' - [R*p]; M = M' - [R*F]
p - суммарный импульс системы, F - равнодействующая сила
*** Уравнение момнентов относительно неподвижной оси X: dL_x/dt = M_x
Внезапно, это просто проекция векторов слева и справа на соответствующие оси. Важного отсюда: ЗСМИ относительно оси:
если момент внешних сил относительно какой-нибудь оси = 0, то и момент импульса относительно этой оси сохраняется.

** QUESTION 12) Движение тел в центральном поле. Закон всемирного тяготения. Законы Кеплера. Финитные и инфинитные движения. Космические скорости. Связь параметров орбиты планеты с полной энергией и моментом импульса планеты.
*** 1 закон Кеплера
все планеты движутся по эллипсам, в одном из фокусов которых находится солнце
*** 2 закон Кеплера
радиус-вектор в равные промежутки времени заметает равные площади
*** 3 закон Кеплера
Кубы больших полуосей относятся как квадраты периодов.
Постоянная Кеплера: a^3/T^2 для произвольной планеты солнечной системы
*** Закон всемирного тяготения.
Любые два тела притягиваются друг к другу прямо пропорционально их массам и обратно пропорционально квадрату расстояния между ними
G - гравитационная постоянная
*** 
** 13) Вращение твердого тела вокруг неподвижной оси. Момент инерции для шара, сферы, цилиндра, стержня. Ур-я моментов. Т. Гюйгенса-Штейнера. Кинетическая энергия вращательного движения.
*** Момент инерции системы относительно оси вращения I: сумма произведений масс материальных точек системы на квардаты их расстояний до этой оси
Пусть м.т. движутся по окружности. Рассмотрим одну: L = p*r = m*v*r = m*w*r^2. Просуммируем для всех, вынесем общую угловую скорость,
а то, что останется под скобкой, обзовем I := ∑mr^2.
*** Основное ур-е динамики вращательного движения: d(Iw)/dt = M, где М - момент внешних сил, I - момент инерции системы
А если I - константа, то получим М = Iϵ, что более употребимо.
*** Ур-е кинетической вращательной энергии:

E = Iw^2. Получается заменой в 1/2*∑mv^2 скорости на w*r.
*** Любое движение системы можно разложить на движение центра масс, и вращение относительно центра масс всей системы
*** НУ покоя тела: сумма внешних сил = 0, и сумма моментов внешних сил = 0
Но оно не есть достаточное: при этом тело может по-прежнему двигаться равномерно-прямолинейно, или вращаться с константной скоростью
*** Гюйгенс-Штейнер: I = I' + ma^2
Пусть O - r, A = r' = r+a. Тогда подставим это вместо r' в ур-е момента инерции отн. А. Заметим, что третий интеграл можно занулить, 
если О проходит через центр масс => то, что надо.
*** Моменты инерции (палки, кольца, цилиндра, диска, сферы, шара)
Везде наша задача - сначала выразить кусочек массы, а через него - кусочек момента инерции, потом проинтегрировать
**** Палка
 dm = m/l*dr => интеграл по палке (-l\2, l\2)
**** Кольцо
выносим общий радиус - очевидно
**** Цилиндр
относительно продольной оси, очевидно, такая же, как и у цилиндра
**** Диск
рассматриваем тонкий слой: 2πr*dr*ρ и интегрируем по ним
**** Сфера
Для начала докажем лемму: сумма МИ относительно трех перпендикулярных осей равна удвоенному моменту инерции отн. точки их пересечения.
// Все вытекает из того, что для подсчета I относительно точки берется растояние до точки, а для подсчета относительно оси - 
кратчайшее расстояние до оси.
Рисуем точку в пространстве массой м, записываем ее Ix, Iy, Iz, суммируем, получаем 2I.
А теперь по поводу сферы. У нее I относительно центра равен m*r^2 (ибо она вусмерть симметричная), и относительно всех осей I тоже
равны между собой. => Ix = 2/3*I = 2/3*m*r^2
**** Шар
dm = m/V * dv, dv = V сферического слоя
Мы знаем, что для сферы: dI = 2/3*dm*r^2. Подставляем dm и считаем интеграл.
 
** QUESTION 14) Плоское движение твердого тела. Качение. Скатывание и подъем по наклонной плоскости.
*** Мгновенная ось
Рассмотрим движение твердого тела. Так как оно твердое, любые две точки в нем будут всегда находится на постоянном расстоянии:
(Rb-Ra)^2 = const
Продифференцируем это, получим: 
(vb - va)(rb-ra) = 0. => Rab(vb-va)=0 //векторные произведения. 
Rab ≠ 0. Следовательно, если мы найдем такую точку A, которая в данный момент неподвижна, то получим Rab*vb = 0
То есть это такая точка, радиус вектор из которой до точки B перпендикулярен скорости в точке B для любой точки B.
Это и есть мгновенная ось.
*** Колесо
Если рассматривать колесо в СО земли, то мгновенной осью будет точка касания с землей. 
Скорость любой точки колеса складывается из скорости поступательного движения колеса и вращательного движения вокруг ЦЕНТРА колеса.
Если это продифференцировать и принять за производную по поступательной компоненте 0 (равномерное качение), то получится, что
вектор ускорения направлен в центр колеса, а не ко мгновенной оси.
*** Угловая скорость как вектор, сложение вращений
Рассмотрим вектор w = [r,v]/r^2, где r - радиус-вектор от оси до точки, v - скорость в точке. 
По модулю эта штука будет равна ω в силу v = ωr, по направлению - совпадает с осью вращения (+ правило буравчика)
// Задача о сложении вращений. Речь только о мгновенных осях и скоростях!
Пусть у нас тело вращается с w1 вокруг оси А, а ось А вращается с w2 вокруг оси B. Какая результирующая скорось тела относительно B?
Его скорость v - сумма скоростей от каждого варщения: v = v1 + v2 = [w1,r] + [w2,r] = [w1+w2,r]
обзовем w = w1 + w2 и получим: v=[w,r].
По поводу того, что r - одинаково: Я так понял, Сивухин подразумевает, что точка находится на одинаковом расстоянии от обоих осей.
// Случай сложения параллельных осей вращения. Сначала - для сонаправленных.
Нарисуем параллелограмм сложения w1 и w2 (немного наклоним друг от друга оси). Проведем перпендикулярную w прямую. w раздели ее соот-
ветственно тангенсам противолежащих углов. Но т.к. углы малы, то тангенсы можно заменить на синусы. А т.к. наклона, который мы сделали
сначала, вообще-то нет, то устремляем α->0 и получаем, что h1/h2 = w2/w1: т.е. мгновенная ось вращения находится между осями обратно 
пропорционально их угловым скоростям. 
Если противонаправлены - то ось находится за осями вращения, на расстояниях h1 и h2 в таком же отношении, как и раньше.
*** Задача о скатывании по наклонной плоскости
с 249 в Сивухине. Я думаю, достаточно просто уметь ее решать и объяснять то, что ты делаешь.
*** QUESTION Задача о поднятии на наклонную плоскость 
В Сивухине нет. Но нужно просто уметь решать, по идее.

** QUESTION 15) Механические колебания материальной точки. Груз на пружине и математический маятник. Частота и период колебаний. Уравнение движения маятника. Роль начальных условий. Колебания маятника под действием вынуждающей синусоидальной силы. Резонанс. Резонансные кривые. Затухающие колебания. Коэффициент затухания, логарифмический декремент затухания, добротность. Период малых колебаний физического маятника.
*** Гармонические колебания: движения, совершаемые по закону x = Acos(wt+ф), A, амплитуда, w - частота, ф - нач. фаза, T=2π/w - период
Дифференцируем раз - получим скорость, еще раз - ускорение. Производная замкнулась => a = -w^2*x, F = ma = -mw^2*x
*** (Закон Гука) F = -kx 
экспериментальный
*** Маятник на пружине
Здесь надо показать, что маятник, который подвешен на пружине в поле тяжести описывается этим же уравнением, просто происходит
сдвиг положения равновесия чуть ниже. Составляем ур-е, заменяем x = X-X0, k = mw^2, получаем:
x'' +wx = 0. - классический дифур. Решаем дифур (с209) и получаем, что x = Acos(wx+ф), с точностью до А и Ф => колебания изохронны (период от
амплитуды не зависит)
Eкин = 1/2*kA^2*sin^2(wt + ф)
Eпот = -//-cos^2
выводится это подстановкой скорости в ур-е кин. энергии
*** QUESTION Математический маятник. 
Нет в Сивухине. Но тут вроде все понятно, выводится тривиально (потренироваться)
*** Роль начальных условий:
есть начальные условия первого и второго рода. Первого - это когда задана координата начала колебаний, а скорость - 0.
А есть, когда координата - 0, но есть начальная скорость.
*** Фазовая плоскость := координатная плоскость (ф, ф'/ω0)
И от времени оно тогда параметризуется, как x = Acos(wt+ф0), y = Asin(wt+w0) - окружность. Удобно: исключили время, иначе бы пришлось
рисовать синусоиду. 
*** Затухающие колебания ф'' + 2δф' + ωф = 0
Возникают тогда, когда есть сила, препятствующая колебаниям. 
Выводится из ур-я моментов на физический маятник (вязкое трение пропорционально ф')
Решение этого ур-я - колебательный контур, затухающий по экспоненте.
*** Действие периодических толчков на незатухающий осциллятор.
Рисунок - фазовый портрет. Пусть мы возбуждаем периодические толчки, причем период толчков несколько не совпадает с периодом маятника.
Тогда мы не сможем возбудить бесконечно сильные колебания: толчки будут сначала помогать раскачиваться, а потом неизбежно начнут мешать.
*** Логарифмический декремент затухания := ln(A(t)/A(T+t)) - логарифм отношения амплитуд через период
Xn - Xn+1 = A - A*e^(-δ*T), гдe -δ*T - логарифмический декремент затухания, что = -A*δT => без толчков затухания происходят в геомет-
рической прогрессии.
А без трения, но с толчками, рост происходил бы как арифметическая прогрессия.
*** Резонанс
Неограниченный рост энергии колебаний при действии силы с периодом, совпадающим с периодом осцилятора.
*** Частота малых колебаний физического маятника.
T = 2π/ω = 2π√(I/mgl). Выводится из уравнения моментов на физический маятник. 
** 16) Неинерциальные СО. Силы энерции. Второй закон Ньютона в неинерциальных СО. Центробежная и кориолисова силы.
*** Неинерциальные СО - СО, у которых есть ненулевое ускорение относительно лабораторной СО
*** Силы инерции - силы, связанные с ускоренным движением системы
выплывают тогда, когда ускорение представляется векторной суммой ускорений системы и усеорений в системе.
*** Второй закон Ньютона для инерциальных СО: ma = F - ma', где a' - ускорение системы
*** Полное уравнение ускорения для произовльно движущейся системы
*** Центробежная и кориолисова силы: Fц = mw^2*r, Fк = 2*m[v*w]
Силы инерции, выводятся из общего ур-я движения
** 17) Элементы теории упругости. Упругие и неупругие деформации. Закон Гука, модуль Юнга, коэффицент Пуассона. Энергия упругой деформации. Деформация прямоугольного параллелепипеда тремя взаимно перпендикулярными силами. Всестороннее и односторонее сжатие. Деформация сдвига и кручения.
*** Упругие и неупругие деформации. 
Упругие - те, после которых образец возвращается в исходное состояние, неупругие - те, после которых он не возвращается. 
У любого образца есть зона упругости, и если мы вышли за нее - то возврата к предыдущим размерам уже нет
*** Закон Гука - деформация упругого тела прямо пропорционально приложенной к стержню силе.
Экспериментальный. Здесь можно нарисовать график текучести
*** Модуль Юнга: E = F/(S*e), он же в T = E*e = F/S
Коэффицент, характеризующий возможности материала сопротивляться внешним воздействиям.
*** Энергия упругой деформации: U = ∫f(x)*dx = k*∫x*dx = 1/2*k*x^2
А если принять за "конечную силу" F = k*Δl, то будет U = 1/2*F*l
*** Плотность энергии u = U/V = 1/2*T*e (V - объем стержня)
*** Коэффицент Пуассона: относительное изменение сечения тела к его относительному удлинению: μ = (Δa/a)/(Δl/l)
**** μ < 1/2 всегда.
*** Растяжение параллелепипеда тремя взаимноперпендикулярными силами
Смысл задачи в том, силы, которые растягивают брусок по оси X, сужают его сечение по оси Y:
ℇx = Tx/E - μ/E(Ty+Tz) - ℇx - относительное удлинение по Х, Tx - натяжение по x, E - модуль Юнга, μ - коэффицент Пуассона
*** Равномерное всестороннее сжатие
P = -Tx = -Ty = -Tz => ℇx = ℇy = ℇz = -P/E*(1-2μ) = Δx/x
ΔV/V = Δx/x + Δy/y + Δz/z = 3Δx/x = -3P/E*(1-2μ) = -P/k, где k - модуль всестороннего сжатия.
Ровно из этой формулы следует, что коэффицент Пуассона < 1/2
*** SMALLQ Плотность упругой энергии:
u = P^2/2k
*** Одностороннее сжатие:
Резинку затолкали в цилиндр на дно и сжимают сверху. Стенки и пол не дают изменить поперечное сечение.
Перерасчет системы в сжатии бруска исходя из доп. условий:
Δy = Δz = 0, Δx = Δl
В итоге μ/(1-μ)*Tx = Ty =Tz
И приведенный модуль Юнга одностороннего сжатия E' = E(1-μ)/(1-μ-2μ^2)
*** QUESTION Деформация сдвига и кручения
Овчинкин сказал, что здесь все работает точно так же, как и в обычном сжатии. Есть в Сивухине
** 18) Уравнение Бернулли для идеальной жидкости. Формула Торичелли. Сила вязкого трения. Вязкость. Стационарное течение вязкой жидкости по прямолинейной трубе. Формула Пуазейля.
*** Идеальная жидкость - жидкость, в которой отсутствует трение.
*** Уравнение стационарного течения: ρ1*v1*s1 = ρ2*v2*s2.
Из того, что это один и тот же кусок массы, проходящий через трубку тока.
А т.к. жидкость почти не сжимаема, ρ можно сократить.
*** Формула Бернулли: v^2/2 + gh + P/ρ = const - константа Бернулли для этого потока.
Рассматриваем два куска жидкости одинаковой массы под двумя разными давлениями с двух сторон трубы. Записываем работу силы давления
по перемещению кусков во внутрь(!) трубы. (даже того, который течет против давления). Рассматриваем разность работы (энергию) и пишем
куда она пошла. 
Вводим удельную энергию e: ΔE = (e2-e1)Δm = A2 - A1 = (P2/ρ2 - P1/ρ1)Δm => e1 + P1/ρ1 = e2 + P2/ρ2 
e = v^2/2 (кинетич) + gh (потенц) + u (вн: для жидкости - почти 0).
Подставляем в то, что выше, и готово.
*** Сила вязкого трения: F = η*S*v/d, где η - коэффицент динамической вязкости, d - расстояние м\у пластинками
Экспериментально
*** Формула Пуазейля: у Овчинкина понятный вывод
*** Формула Торичелли: v = √(2*g*h), где v - скорость потока из тонкого отверстия на глубине H.
Легкий вывод на Википедии. 
** 1) Идеальный газ. Давление идеального газа как f(Ek). Связь T и Ek. Ур-е состояния идеального газа. Внутренняя энергия идеального газа.
*** (Первое начало термодинамики) Любая изолированная система со временем переходит в состояние термодинамического равновесия
Естесственно, если систему не трогать. Эмпирический факт.
*** Стационарное состояние: когда параметры не меняются
в замкнутой системе === ТДР. В открытой - какое угодно.
*** (Релаксация) Процесс прихода в новое стационарное состояние
r - время релаксации
*** Квазистатический (равновесный) процесс: такой, что система в каждый момент времени находится недалеко от какого-то состояния равновесия
например, если мы по чуть-чуть подогреваем воду, то она успевает каждый раз возвращаться с статическое состояние.
Всякие там графики на диаграмах (которые неперывные) - графики равновесных процессов: в каждой точке графика - ТДР.
Неравновесный обычно обозначается прямой пунктирной линией, его промежуточные состояния не описываются макропараметрами и смысла не несут.
*** (Обратимый процесс) - м.б. проведен в обратном направлении через те же состояния, что и "туда", и при этом в итоге ничего не должно измениться
*** Идеальный газ - взаимодействием молекул можно принебречь
Кинетическая энергия много больше энергии взаимодействия. Нейтральный газ там, например.
*** (Давление ид. газа) P = 2/3*n*Ek - Ek - средняя кинетическая энергия одной молекулы. n - число молекул в единице объема.
вводим n(v) - число молекул со скоростью V в единице объема газа. 
Рассмотрим то, что происходит у стенки за время dt. Для каждой V такой, что Vx >0 до стенки долетят все молекулы, которые к ней 
ближе, чем Vx*dt => их ровно n(v)*S*Vx*dt. Каждая молекула приносит импульс Px. Суммируем по всем скоростям с положительной компонентой
, получаем импульс = сила *dt. Делим на dt и S, получаем давление. Потом финт ушами: 
1) говорим, что молекул, которые Vx>0 ровно половина, сокращаем двойку и расширяем границы суммирования
2) заменяем Vx*Px на их среднеарифметическое, тогда от суммы зависит только n(v) => остается n*Vx*Px
3) в силу изотропности газа, PxVx=PyVy=PzVz => делим на три и убираем все иксы
Получили P = 1/3*n*v*p. Замечаем, что vp = 2*Ek => то, что надо.
*** (Связь T и Ek) Ek = 3/2*kT, где Ek - средняя кин. энергия одной молекулы
Возьмем предыдущую формулу. Заметим, что n*E*V - полная кин. энергия газа в объеме V.
PV = 3/2*Eполн = μRT из Менделеева-Клапейрона. E = EN = EμNa. Подставляем, заменяем k = R/Na (больцман), получаем то, что надо.
*** (Ур-е состояния идеального газа) PV=μRT. И тип все.
*** Внутренняя энергия: см п.2
** 2) Работа, теплота, внутренняя энергия. Первое начало термодинаммики. Теплоемкость и ур-е Майера. Адиабатический и политропический процессы. Ур-я адиабаты и политропы для идеального газа.
*** Работа: над системой: dA = Pвнеш(-dV), системы: dA = P*dV
Работа еще площадь под PV-графиком. По часовой стрелке - положительная, против - отрицательная
Изобар: A = P*ΔV, изотерма: A = μRT*ln(V2/V1) - подстановка P из Менделеева и интеграл.
*** Адиабатическая оболочка: не пропускает тепло. Работу над газом в оболочке можно совершить только механически.
*** Внутренняя энергия: A = U2-U1. 
Если система заключена в адиабатическую оболочку, то работа внешних сил не зависит от траектории процесса, а поэтому определяется
дельтой функции состояния газа := внутренней энергией.
Внутренняя энергия зависит только от температуры, и, исходя из теплоемкости, может быть выражена:
dU = Cv*dT => U = ∫Cv(T)*dT
Так, например, для одного моля идеального газа U = 3/2*RT
*** Теплота = количество теплоты = приращение внутренней энергии в следствии процесса чистого теплообмена. 
Как будто мы заключили газ в теплопроводящую, но крепкую, оболочку.
*** Первое начало термодинамики: dQ = dU + dA: тепло, переданное системе идет на совершение ей работы и изменение ее вн. энергии.
*** Теплоемкость: := C = (dQ/dT) - кол-во теплоты, необходимое для изменения температуры на 1 градус. Разделяется для процессов:
Сp - для изобары = δH/δT, где H := U + PV - энтальпия. 
Cv - для изохоры = δU/δT.
оба выражения получаются дифференцированием первого начала по dT и занулении того, что фиксировано в этом процессе.
*** Уравнение Майера: Cp = Cv + μR.
Подставляем dU = Cv*dT (вып-ся для любого идеального газа, ибо внутренняя энергия зависит только от температуры) 
и ур-е МК для PV в ур-е для Cp, и получаем то, что надо.

Пусть γ = Cp/Cv => Cv = 1/(γ-1)*μR, Cp = γ/(γ-1)*μR
*** Адиабатический процесс: подвод тепла = 0.
Ур-е адиабаты следует из 1Нч.Т.: вместо P - ур-е МК, вместо dU - Cv*dT. Потом химичим с известными соотношениями и получаем 
T*V^(γ-1)=const. С помощью МК можно переписать и в виде PV^(γ) = const
*** QUESTION Политропический процесс: процесс, в котором теплоемкость не меняется.
// не понял как это вывести
Формула: PV^n = const, где n - показатель политропы.

** QUESTION 3) Второе начало термодинамики. Формулировки второго начала. КПД тепловой машины. Цикл Карно. Теорема Карно. Неравенство Клаузиуса.
*** Формулировка Клаузиуса: невозможен круговой процесс, ед. рез-том работы которой была бы передача тепла от более холодного резервуара к более горячему.
*** Формулировка Томпсона: невозможен круговой процесс, ед. рез-том работы которой было бы совершение работы за счет теплоты, взятой одного и того же тела
*** Эквивалентность формулировок: Машина Клаузиуса возможна <=> машина Томпсона возможна.
<= совершаем работу по нагреву резервуара = машина Клаузиуса
=> подключаем между двумя резервуарами параллельно обычную тепловую машину (которая совершает работу) и машину Клаузиуса
*** (Цикл Карно) Обратимый цикл, состоящий из двух изотерм и двух адиабат.
*** QUESTION КПД: μ = A/Q - отношение работы, которую совершила машина, к затраченной на это энергии нагревателя.
//вопрос про стрелки
Если это машина, которая подключена к двум резервуарам и качает тепло одного другому, то μ = 1 - Q2/Q1.
*** КПД цикла Карно: μ = 1-T2/T1.
Аккуратная адиабатическая химия. Но вроде это не надо.
*** Теоремы Карно:
**** 1) КПД любых идеальных машин, работающих по циклу Карно над двумя одинаковыми резервуарами, равны, независимо от их внутреннего строения
Пусть есть две Карно-машины с КПД = μ1 и μ2. Для определенности, μ1 < μ2. 
Поместим машины между двумя резервуарами: нагревателем и холодильником. K1 выдает работу A и переносит остаток тепла в холодильник,
К2 забирает часть тепла, потребляет работу А' и за счет нее переносит сумму в нагреватель.
Пусть A=A1 (мы так умеем). Тогда:
0 = A - A1 = (Q1-Q2) - (Q1' - Q2') = μ1*Q1 - μ2*Q1' => Q1 = μ2/μ1*Q1' => в нагреватель льется тепло
то же самое для холодильника => из холодильника тепло качают => сделали машину Клаузиуса. Ой... => μ2 ⩾ μ1.
Проворачиваем все то же самое => μ2 = μ1
**** 2) КПД любой тепловой машины не может превышать КПД машины Карно на тех же резервуарах. 
То же самое, только менее эффективная машина дана сразу => достаточно провернуть первое док-во один раз и придти к противоречию
*** QUESTION Неравенство и равенство Клаузиуса: Q1/T1 + Q2/T2 ⩽ 0, где Q1 и Q2 - ПОДВОД тепла к 1 - нагревателю, 2 - холодидльнику
из того, что μ ⩽ μk => 1 - Q2/Q1 ⩽ 1 - T2/T1. //Q2 = -Q2 - отток =-приток.
Равенство достигается для машины с обратимым процессом, работающей с двумя резервуарами. // почему?
Чтобы вывести общее неравенство Клаузиуса, соберем систему, из N термостатов, передающих тепло системе А. В них из общего резервуара
Т0 накачивают тепло N машин Карно, причем так, чтоб подкачка тепла в термостаты была ровно такая, сколько термостаты отдают тепла. 
Тогда для одной машины Карно можно расписать равенство Клаузиуса, а потом посуммировать. В итоге получится, что 
тепло, переданное системе А от резервуара T0 есть Q0 = T0*∑Qi/Ti. Но тк. система А осуществляет произвольный круговой процесс, то ее
работа по Томсону (холодильника нет) может быть только отрицательной => A = Q0 = T0*∑Qi/Ti M ⩽ 0. Разделим на T0 и получим нерав-во
Клаузиуса.
А теперь пусть процесс обратим: можно сделать ту же последовательность шагов в обратном направлении и получить возврат тепла за счет 
работы => достигается равенство нулю.
Перейдем к бесконечному числу машин и термостатов и проинтегрируем по ним => получим неравенство в интегральной форме.

** 4) Термодинамическое определение энтропии. Закон возрастания энтропии. Энтропия в идеальных газах. Энтропия в обратимых и необратимых процессах.
*** Энтропия: ΔS = ∫dQ/T, закон возрастания энтропии
Выходит из неравенства Клаузиуса. Рассмотрим равенства (только обратимые процессы):
0 = ∫dQ/T = ∫(1,2)dQ/T + ∫(2,1)dQ/T
Сменим порядок обхода второго контура (но путь разный!). Получится, что это дело от пути не зависит и есть функция состояния.
Так и назовем ее - энтропия. И для обратимых процессов (равенство Клаузиуса) она есть 0. А вот для необратимых (неравенство) она воз-
растает: ΔS > 0.
*** Энтропия в идеальных газах. S = S0 + μ(Cv*dT/T + R*dV/V)
возьмем второе начало: dQ = dU + PdV и подставим dQ = TdS, разделим все на T и повыносим. Получим:
dS = μ(Cv*dT/T + R*dV/V). Проинтегрируем разок и получим то, что надо.

*** Термодинамические потенциалы - это функции, которые при задании ряда параметров системы позволяют находить все остальные.
В сущности, все три - просто по-разному переписываемое первое начало.
*** Внутренняя энергия
dU = TdS - PdV
Изменение внутренней энергии равно притоку тепла при изохорическом процессе, или работе над системой при адиабатическом процессе
*** Энтальпия: H(S,P) = U + PV
dH = TdS + VdP
Равно, например, теплу, полученному системой в изобарном процессе
*** Свободная энергия Гельмгольца: F(T,V) = U - TS
dF = -SdT - PdV
Равно, например, -теплу, полученному системой в изохорном процессе, или работе, совершенной в изотермическом процессе

*** QUESTION Потенциал Гиббса
** QUESTION 5) Фазовые переходы. Кривая фазового равновесия. Ур-е Клапейрона-Клаузиуса. Диаграма двухфазной системы "жидкость-пар". Критическая точка. Тройная точка. Диаграма состояния "лед, вода, пар". Метастабильные состояния. Перегретая жидкость и переохлажденный пар.
*** Фаза - физически однородная часть сиситемы, отличающаяся по своим св-вам от других частей и отделенная от них четко выраженной границей
*** Фазовый переход - переход из одной фазы в другую 
*** Химический потенциал системы - измененние энергии системы при добавлении одной частицы вещества
+ одно слагаемое справа: μdN в первом начале.
Химический потенциал есть термодинамический потенциал в расчете  на одну частицу
*** Условие равновесия фаз: P - const, T - const, μ - const
//картинка с двумя фазами внутри адиабатической оболочки
Док-во последнего утверждения - записать два первых начала (для первого и второго моментов), сложить вместе и посокращать. 
Приравнять энтропию к нулю (ТДР). Получится μ2=μ1
*** Клаузиус-Клайперон: dP/dT = q12/T(v2-v1)
где q12 - тепло фазового перехода в расчете на одну единичу вещества
v2,v1 - удельные объемы на одну частицу вещества: V/N

Вывод:
Мы знаем, что μ = Ф/N (химический потенциал это удельный термодинамический потенциал, да)
Запишем второе начало через Ф:
dФ = -SdT + VdP + μdN
подставим, получим: dμ = -s*dT + v*dP, где s = S/N, v = V/N
А еще, мы уже доказали, что μ1(P, T) = μ2(P,T). Вот и запишем это для двух состояний, получим:
dP/dT = (s2-s1)/(v2-v1). Переобозначим T*(s2-s1) = q12 - удельная теплота перехода между фазами
dP/dT = q12/T(v2-v1) - то, что надо
*** Фазовая диаграма
У нас есть ур-е μ1(P,T) = μ2(P,T) - условие сосуществования фаз. На диаграме P,T начертим линию, которая удовлетворяет этим соотношениям.
*** Диаграмма двухфазной системы "жидкость-пар"
    Есть ур-е Клайперона-Клаузиуса. v2 >> v1 (пар же), q12=q. Еще воткнем в него УМК в виде P*v2 = kT
получим dP/dT = q/kT^2*P. Знаем начальные условия: P(T0) = P0 Решаем относительно P, получаем:
P = P0*exp(q/kT0 - q/kT) - возрастающая по Т экспонента, оно и надо.
*** Критическая точка
Точка, в которую упирается кривая фазового равновесия где-то при высоких температурах, и когда уже вещество находится в однородном
состоянии и двух фаз не возникает. 
Критическую точку можно обходить сверху (с сохранением однородности в-ва) или перейти через фазовую кривую (с появлением двух
разделенных фаз).
*** Тройная точка
Если контакр
** QUESTION 6)Газ Ван-Дер-Вальса, как модель реального газа. Изотермы Ван-Дер-Вальса. Уравнение адиабаты Ван-Дер-Ваальса. Критические параметры и приведенное уравнение. Правило Максвелла и правило рычага. Внутренняя энергия и энтропия газа ВдВ. Эффект Джоуля-Томсона.
*** Ур-е Ван-Дер-Вальса: (P + a*(μ/V)^2)(V - μB) = μRT
Поправка к объему - это объем занимаемый молекулами (молекулы не могут быть друг в друге)
Поправка к давлению: 1) частота соударений ~ n; 2) сила со стороны газа ~ n => ΔP ~ n^2, n = P/kT
*** Изотермы Ван-Дер-Ваальса
Ведут себя немонотонно: при T <= Tкр есть экстремум (минимум). 
Все эти минимумы лежат на ГМТ dP/dT = 0.
Сей график есть спиноидаль: P = (V - 2b)a/V^3. 
Ее максимум - это точка, где минимум изотермы сливается в прямую и вырождается. Эту точку называют критической точкой.
Поиск критической точки - первая и вторая производная = 0. (ищем максимум спиноидали).
Решение ур-я дает: Vкр = 3b, Pкр = a/(27*b^2), Tкр = 8a/27b^2
В итоге, получаем ур-е "критической изотермы": Pкр*Vкр = 3/8*Tкр. - ур-е характеризует связь координат критических точек для различных изотерм
*** Ур-е адиабаты Ван-Дер-Ваальса
*** QUESTION Критические параметры и приведенное уравнение
Давайте все три макропараметра P,V,T поделим на их критические значения для этого газа. Получится три безразмерных параметра - единицы
критических значений: π = P/Pкр, ф = V/Vкр, τ = T/Tкр
Тогда можно записать приведенное уравнение Ван-Дер-Ваальса:
(π + 3/ф^2)(ф - 1/3) = 8/3*τ
В этом уравнении выполняется закон соответствия состояний: для любых газов одним и тем же значениям приведенных объема и давления соот-
ветствуют одни и те же значения приведенной температуры.

// что есть критические параметры
*** Правило рычага
*** QUESTION Правило Максвелла
*** Внутренняя энергия и энтропия газа Ван-Дер-Ваальса
*** Эффект Джоуля-Томсона

** 7)Поверхностные явления. Свободная энергия поверхности. Краевые углы. Смачивание и несмачивание. Формула Лапласа. Зависимость давления пара от кривизны поверхности жидкости. Роль зародышей в образовании новой фазы.
*** Поверхностная энергия: избыток потенциальной энергии на поверхности
Все молекулы притягиваются друг к другу. Особенно те, которые находятся в пределах "эффективного радиуса взаимодействия",
порядка 2-3 радиусов молекулы. Вблизи поверхности с одной стороны молекул меньше, поэтому возникает сила, втягивающая молекулу вовнутрь.
Внутри же обычно силы скомпенсированы => возникает избыток потенциальной энергии на поверхности.
*** Поверхностное натяжение:
Работа, которую нужно затратить для увеличения площади поверхности на единицу в изотермическом процессе, не меняя при этом объема
Пусть теперь внутренняя энергия складывается из Fоб - объемной и Fп - той, что на поверхности. Второе пропорционально площади =>
F = σS, где σ - коэффицент поверхностного натяжения.

Работа на то, чтобы растянуть пленочку, на которую с двух сторон действует стягивающая сила f, равна 2f*dx. Но это равносильно
изменению ее площади на l*dx = dS, что увеличивает внутреннюю энергию на σ*dS, а это и есть работа. Приравниваем => σ = f/l
*** Краевой угол: угол на месте контакта двух сред (например у капли на металле)
Можно оценивать эти углы. Используем σ как силы на единицу длины, дабы в точке контакта записать 2 ур-е Ньютона.
Записываем, проектируем по осям, решаем.
*** Смачивание и несмачивание
после записи уравнений на краевые углы будет видно, при каком отношении натяжений ур-я не имеют решения. 
1) cos > 1. В этом случае ф = 0 капля полностью растекается по поверхности среды (другой жидкости или твердой поверхности), 
или, иначе - поверхность смачивается. Смачиваемая поверхность называется лиофильной (или гидрофильной)
2) cos < -1. ф = π и капля образует шарик на поверхности, и поверхность не смачивается (лиофобная).
Или, когда решение есть:
3) ф ∈ (0, π/2) - частичное смачивание
4) ф ∈ (π/2, π) - частичное несмачивание
*** Формула Лапласа: Pвн - Pcн = σ(1/R1 + 1/R2)
Формула позволяет находить разность давлений под поверхностью и над поверхностью выпуклой оболочки жидкости.
Рисуем "кусочек сыра": площадку на круглой поверхности размерами dx*dy: ABCD. По сторонам AB и CD радиус до центра R1, по AC и BD - R2.
Ищем равнодействующую сил, которые растягивают противоположные стороны квадрата (через синус угла при радиусе и 1/2*sin(a/2) ~ a/2).
Получаем для обоих сторон dF1 = dS*σ/R1, dF2 = dS*σ/R2. Берем сумму и делим на dS, получаем разность давлений => то, что надо.
*** Кипение
Фазовый переход "жидкость-пар", в процессе которого пузырьки пара образовываются посреди жидкости. 
*** QUESTION Роль зародыша (пузырька)
** 8) Распределение Максвелла. Распределение частиц по компонентам скорости и по абсолютным значениям скорости. Доля молекул, лежащих в заданом интервале скоростей. Наиболее вероятные средние и среднеквадратичные скорости.
*** Распределение Максвелла: dn(v)
*** QUESTION Распределение частиц по компонентам скорости: 
*** Распределение частиц по абсолютным значениям скорости:
*** Распределение по абсолютному значению скоростей:
у нас есть dn(v) = n*Ф(v)*d^3(v)
Выпишем в явном виде Ф(v), раскрыв d^3(v) как шарик, получим искомую формулу распределения
*** Доля молекул в диапазоне скоростей: интеграл от v1 до v2 по функции распределения.
*** Наиболее вероятная скорость: v = √(2kT/m) - результат Ф'(v)=0
*** Среднеквадратичная скорость: корень из среднего квадрата скорости = √(3kT/m) 
как корень из интеграла по v^2 * Ф(v) по всему диапазону скоростей
*** Средняя скорость: √((8/π)*(kT/m))
как интеграл по v*Ф(v) - стандартный способ посчитать среднее значение
** 9) Распределение Максвелла по импульсам и энергиям. Среднее число ударов молекул о стенку. Средняя энергия утечки в вакуум.
*** Распределение по энергиям: подстановка v = √(2e/m) => Ф(e)
*** Распределение по импульсам: подстановка v = p/m => Ф(p)
*** Число ударов молекул о стенку: j = 1/4*n*v, 
где j - поток (число частиц через единичную площадочку в единицу времени, n - всего частиц, v - средняя скорость
// рисунок про телесный угол на стенку:
пусть dn(v) - объемная плотность частиц со скоростью v. Тогда в сторону площадочки летит dΩ/4π частиц (наш телесный угол к полному)
За время dt до площадочки долетят: dS*v*cosф*dt*dΩ/4π частиц, где dΩ = 2π*sinф*dф.
Интегрируем по скорости (0, +∞), по углу (0, π/2) и получаем то, что надо.
*** Средняя энергия утечки в вакуум: e = 2kT
число частиц со скоростью v в единичном объеме: dn(v) = n*Ф(v)*dv
доля потока через дырку с этой скоростью: dj = 1/4*v*dn
а энергию каждая такая доля уносит: dE = 1/4*v*dn*mv^2/2
средняя энергия e = E/j = (∫dj*mv^2/2)/(∫dv) = 2kT (после кучи сокращений)
Важный момент: эта энергия больше средней энергии молекулы (3/2kT) => улетают более быстрые частицы => бак охлаждается 
** 10) Распределение Больцмана в однородном поле сил. Барометрическая формула.
*** Барометрическая формула: P = P0*exp(-mgz/kT)
Мы хотим решить задачу "как изменяется давление атмосферы с ростом выстоты". Рассматриваем кусочек слоя на высоте z, толщиной dz и 
площади S. Пусть на него действует объемная сила на одну частицу = f. Тогда для слоя, находящегося в равновесии, имеем:
f*N + P(z)*S - P(z+Δz) = 0, где N = n*S*dz, n - объемная плотность частиц.
Переносим влево, делим на S*dz, замечаем производную и имеем:
dP/dz = f*n. 
Теперь хинт: P = nkT => подставляем n, заносим P под производную. Далее, пусть сила f - потенциальна: f = -δu/δz.
d(lnP)/dz = d(-u/kT)/dz. Навешиваем интеграл, потенциируем, и имеем то, что надо.
*** Распределение Больцмана: dN = n0*exp(-mgz/kT)*dV
в барометрическую формулу подставляем P = nkT и домножаем на dV.
** QUESTION 11) Теплоемкость. Классическая теория теплоемкости. Закон равномерного распределения энергии теплового движения по степеням свободы. Теплоемкость идеальных газов при постоянном объеме и постоянном давлении. Теплоемкость кристаллов (Дюлонг-Пти)
*** Теорема о равнораспределении энергии по степеням свободы
Если система подчиняется законам классической механики, то на каждое слагаемое в энергии, квадратично зависящее от скорости или коорди-
наты, приходится по kT/2 энергии и по k/2 теплоемкости. 
Рассмотрим все три степени свободы:
**** Поступательная
Eпост = 3/2*k*T => на одну степень - kT/2
С = dEпост/dt = 3/2*k => на одну степень - k/2
**** Вращательная 
Eвр = Iw^2/2 (по осям).
Подставим в Гиббса, продифференцируем (ищем скорость, соответствующю наибольшей вероятности)
получаем, что wx = kT/Ix, ... подставляем назад => Eвр = 3/2*k*T => по kT на осью
**** QUESTION Колебательная 
*** Закон Дюлонга-Пти: для кристаллов Cv = 3R
В кристаллах молекулы колеблются около своего положения равновесия => имеют 3kT (?!) степеней свободы (только колебательные)
тогда в одном моле энергии:E = 3*Na*k*T => Cv = dE/dT = 3*Na*k = 3R.
** 12) Эффективное газокинетическое сечение. Длина свободного пробега.
*** Эффективное газокинетическое сечение - площадь сечения молекулы (ну, или сечение цилиндра, который она вырисовывает при своем движении)
Если молекулы разные, то сечение можно определить как π(r1^2+r2^2)
*** Длина свободного пробега молекулы: l = 1/(nσ), время свободного пробега t = l/v
За время t молекула пройдет расстояние l=vt, и опишет цилиндр объема V = σl. Число частиц в нем = nσl. Будет хотя бы одно столкновение,
когда nσl = 1 => то, что надо.

Формулу можно уточнить исходя из предположения о том, что все молекулы движутся. Мы знаем, что средняя скорость молекулы связана
с ее скоростью относительно других молекул, как Vотн = Vср*√2. => используем эту скорость, и получаем l = 1/(nσ√2)
*** Частота столкновений молекул.
частота столкновения одной молекулы: f' = (l/V)^-1. Всего столкновений f = 1/2*n*f'. 
Замены: n из P = nkT, σ = πd^2, v = формула для средней скорости частицы
привели и получили то, что надо.
** QUESTION 13) Явления переноса: вязкость, теплопроводность и диффузия. Законы Фика и Фурье. Коэффиценты вязкости, теплопроводности и диффузии в газах
*** Диффузия: явление пространственного перераспределения компонент смеси относительно друг друга (перемешивание)
*** Закон Фика: j1 = -D*n*d(c1)/dx, j2 = -D*n*d(c2)/dx, j1+j2=0
Пусть у нас есть плотности компонент n1 и n2, n = n1+n2 (частиц/V). Тогда c1 = n1/n, c2 = n2/n. - Концентрации компонент. 
И дальше просто сразу пишем закон Фика. 
D - коэффицент диффузии (см/с).
Если n = const, то можно n удалить из формулы.
Если сам по себе газ куда-то движется, то нужно добавить еще одно слагаемое: n*ci*u:
j1 = -D*n*d(c1)/dx + n*c1*u; j2 = -//-. j1 + j2 = nu
*** Теплопроводность: неравновесный процесс передачи тепла от более нагретого тела к менее нагретому
*** Закон Фурье: q = ℵ*dT/dx:
q - поток тепла (кол-во теплоты, пересекающее единичную площадку в единицу времени)
ℵ - коэффицент теплопроводности.
*** Вязкость: сила вязкого трения, действующая по площади S на слой жидкости (газа), параллельный направлению движения, со стороны нижележащего слоя
*** Закон Ньютона: Fz = -μS*du/dx
*** QUESTION Оценка коэффицентов вязкости, теплопроводности и диффузии
