* Матан
** 1) Предел числовой последовательности, теорема Вейерштрасса о пределе монотонной последовательности
*** [#A] Определение предела, определение отрицания предела
    Стандартное, через e. Отрицание предела - ∃e>0 что за него последовательность хоть где-то да выйдет
*** Лемма о единственности предела последовательности
    a и b - два предела одной последовательности. Рассмотрим непересекающиеся окрестности - когда-нибудь последовательность зайдет
    и туда и туда, что бред
*** Последовательность ограничена с n0 → ограничена везде
    После ограничена, а до - возьмем супремум и инфиум конечной части
*** Сходящаяся последовательность ограничена
    Начиная с какого-то n для ϵ = 1 по определению оно огр. a ⨦ 1, поэтому верно по предыдущей лемме.
*** Последовательность нснм по модулю больше половины своего предела, причем с сохранением знака
    a > 0 - предел. Рассмотрим ϵ = a/2. По определению - раскроем модуль и получим то, что надо. Потом для a < 0 так же.
*** Лемма о сохранении знака - знаки предела и посл. совпадают начиная с какого-то n
    прямо следует из предыдущей
*** Определение бесконечно-малой последовательности (бмп). Любую посл. м. представить как сумму ее предела и бмп.
    рассмотрим бмп = последовательность - предел. Покажем по опр, что она - бмп.
*** [#B] бмп + бмп = бмп.
    для любого ϵ можем выбрать общий (max) n0, что они обе меньше ϵ\2. => сумма < ϵ
*** бмп * огр = бмп, бмп*С = бмп, бмп*бмп = бмп
    1) пусть огр < C, тогда бмп нснм < ϵ/c. => произведение < ϵ
    остальное сразу следует из 1.
*** Предел суммы, произведения и частного (b != 0) равен сумме, произведению и частному пределов
    Везде сначала раскладываем последовательность на сумму предела и бмп, потом 
    1) a + b + бмп = a+b
    2) все - бмп, кроме a*b
    3) Берем n после которого yn != 0. Пишем xn/yn -a/b, выносим 1/yn, получаем огр*бмп.
*** (предельный переход в неравенстве) Если нснм xn <= yn, то и a <= b.
    1) от прот: рассм. непересекающиеся окр. a и b. нснм последовательности зайдут в свои окрестности и будет противоречие: xn>yn.
*** (Лемма о двух мажорантах) limXn = limYn = a, Xn <= Yn <= Zn => limYn = a.
    Фиксируем e. Тогда рассмотрим n, когда Xn и Zn уже в этой окр. Соответственно, Yn тоже зажата м-у a-e и a+e начиная с этого n =>
    limYn = a по опр.
*** [#A] (Т. Вейерштрасса) монотонно возр и огр сверху => имеет предел равный sup. // Аналогично для убывает и inf
    Рассм. α = supXn. ∀e > 0 ∃n ∀nk > n: a-e < Xnk ⩽ a (ибо возр). => нснм Xnk ∈ Ue(a) => a - предел по опр.

** Вспомогательные штуки
*** Теорема Кантора о вложенных отрезках: вложенные отрезки имеют как минимум одну общую точку. А если их длины убывают - единственную.      
    Влож отрезки: ...[an, bn] ∈ ... [a1, b1] → a1 <= a2 <= .. <= an ... <= bn <= ... <= b1. Рассмотрим посл. {an} и {bn}. 
    an огр. сверху любым b, bn огр снизу любым a => существуют supAn = γ1 и infBn = γ2. [γ1, γ2] - пренадлежит всем отрезкам.
    Теперь, если |an - bn| → 0 => an ⫹ γ1 ⫹ γ2 ⩽ bn => γ1 = γ2 = γ = limAn = limbn по т. Кантора
 
*** 6 стандартных предельных символов (6 СПС)
a, a+0, a-0, +∞, -∞, ∞
** 2) Частичный предел числовой последовательности. Теорема Больцано-Вейерштрасса
*** [#A] Опр. частичного предела последовательности Xn
a - ч. пр, если ∃ Xnk - строго возр подпосл. такая, что limXnk = a.
*** Предел любой подпоследовательности равен пределу последовательности, если он есть
Рассматриваем U(a ∈ СПС). Внутри - если посл зашла, то подпосл тоже. Вне окр - конечное число эл-тов.
Следствие - если предел ∈ R, то он же - единственный ч. пр.
*** (Критерий ч.пр) a ∈ (R, +∞, -∞) - ч.пр. Xn <=> в любой Ue(a) Xn ∃ беск. число членов Xn
=> Если оно ч.пр, то вне любой окрестности содержится не более, чем конечное число членов ряда => внутри окрестности все остальные(∞)
<= Строим подпосл: Xk1 ∈ U1(a), xk2 ∈ U_1/2(a) ... т.к. в любой окр содержится ∞ членов, то мы всегда возьмем один - беск посл
со строго возр. индексами. Т.к. Xkt ∈ U_1/t(a) => a - 1/t ⩽ Xkt ⩽ a + 1/t => по лемме о двух мажорантах limXkt = a. 
Для беск. нужно брать //доделать 
*** [#A] (т. Больцано-Вейерштрасса) Любая огр. посл. имеет сх. подпосл.
Xn - огр => лежит в отрезке [a, b]. Разобьем отрезок пополам и возьмем ту половину, где Xn - бесконечно много (если в обоих
бесконечно много - то любую). И так рекурсивно. μ[An, Bn] = (b-a)/2^n -> 0 => по т. Кантора есть ровно одна общая точка c.
Фиксируем e. Т.к. ∃n0, что ∀n>n0 μ[An, Bn] < e (=> ∈ Ue(c)), причем там ∞ Xn, то по критерию ч.пр. с - частичный предел.
*** (о единственном ч.пр) Xn - огр и имеется ровно 1 ч.пр. =a, то Xn -> a. 
Xn - огр => Xnk => огр => a ∈ [m, M]. Пусть a - не предел Xn, =>  ∃ e>0, что вне Ue(a) б.м. членов Xn (пусть справа) => по ТБВ
на [a+e, M] имеется частичный предел => противоречие тому, что он один.
** 3) Критерий Коши сходимости последовательности
*** (Критерий Коши) Xn - сх <=> Xn - фунд.
=> пусть a - предел. Фиксируем e, тогда ∃n0, что | | < e/2. Берем n>n0 и m > n0: |xn -xm| = |(xm - a) + (a - xm)| <... < e.
<= Докажем, что оно огр: фиксируем e = 1, тогда ∃n0, ∀n, m ⩾ n0 |xm - xn| < 1 Фиксируем m = n0 => |xn| ... < 1 + |xn0| => огр 
начиная с n0 => огр везде => по ТБВ ∃ ч.пр. Чтобы доказать, что он - предел всей Xn, докажем, что он один. 
От противного, пусть их два: b > a. Пусть e = (b-a)/3 (из опр. фунд) => ∃n0, что |xn - xm| < e. Но т.к. вокруг каждого предела
бесконечно много элементов Xn, то найдутся n1, n2 > n0, что Xn1 ∈ Ua, Xn2 ∈ Ub => противоречие, ибо между окрестностями зазор > e.

** 4) Опеределения предела функции по Коши и по Гейне, их эквивалентность. Критерий существования предела по Коши. 
*** Определение по Коши 
limf(x) = b при x->a :=  ∀e > 0 ∃δ(e)>0 |x-a| < δ => |f(x) - b| < e
*** Определение по Гейне
-//- := ∀Xn: limXn = a => limf(Xn) = b при n -> ∞
*** Эквивалентность Коши и Гейне
=> Возьмем {Xn} такую, что limXn = a (xn ≠ a). Зафиксируем e, подберем такой номер n0, что ∀n>n0 |xn-a| < δ. Но из этого следует,
что |f(xn) - b| < e. В силу произвольности Xn, это предел по Гейне.
<= Возьмем отрицание Коши: существует e, что какую бы δ мы не взяли, найдется U(a), что f(x) !∈ U(b)
Пусть δ = 1/n => есть {Xn}, что ∀n ∈ N Xn в 1/n-окрестности a, но при этом f(Xn) вне e-окрестности b. По лемме о двух мажорантах, 
limXn = a => по гейне limf(xn) = b. Делаем предельный переход - получаем противоречие.
*** Много переходных лемм, аналогичных билету 1.
Доказательства в духе: возьмем рандомную подпоследовательность, воткнем ее в наши функции и рассмотрим это как новые последовательности.
По соответствующим леммам, для последовательностей работает => для функций работает в силу рандомности последовательностей.
*** (Критерий Коши существования предела функции) Функция имеет предел b в точке a <=> функция "фундаментальна в точке a"
=> Из предела по Коши берем x1 и x2 из δ-окрестности такие, что |f(x1 и x2) - b| < e. Дальше |f(x1)-f(x2| = |f(x1) - b.... | <...<e   
<= Возьмем Xn такой, что limXn = α и покажем, что f(xn) - фундаментальна (используя усл-е) => имеет предел.
Теперь докажем, что произвольно взятые Xn будут иметь один и тот же предел. Пусть нет: Xn->α, Yn->α, но f(Xn)->a, f(Yn)->b. 
Склеим Xn и Yn (x1, y1...) , получим Zn -> α. Но у него не будет предела, ибо есть два частичных предела. Противоречие.

** 5) Свойство непрерывной функции на отрезке, т. Вейерштрасса и Больцано-Коши
*** Что такое свойства?
*** Непрерывность на отрезке [a, b] => непрерывность во всех точках интервала (a, b), непрерывна справа в a, и слева в b
*** (Первая т. Вейерштрасса) f - непр. на [a, b] => f - огр на [a, b]
Пусть это не так: тогда ∀e>0 ∃x ∈ [a, b] f(x) > e. Будем подставлять e = 1, 2, 3..., получим {xn} такую, что |f(xn)|>n. 
Xn ∈ [a, b] - огр, тогда ∃Xnk - сх. (пусть к точке x0 ∈ [a, b] т.к. xnk ∈ [a,b]). f - непр => lim(f(Xnk)) = f(x0). Но, при этом, 
f(Xnk) > nk >=k (как возр. индексы подпосл). => f(Xnk) -> ∞ при k -> ∞. Противоречие.
*** (Вторая т. Вейерштрасса) f - непр. на [a, b] => f достигает своих sup и inf на [a, b]
Sup и inf существуют (ибо f - огр по Вейерштрассу1). Пусть sup = M. Тогда ∀M'<M ∃x: f(x)>M'. Будем подставлять M' = M-1/n, 
получим последовательность Xn ∈ [a, b] => ∃ Xnk - сх к X0. но т.к. ф-я непрерывна в x0, то limf(Xnk) = f(x0) при k->∞. 
Но f(Xnk)->M, так что f(x0) = М в силу единственности предела.
*** (т. Больцано-Коши) f - непр. на [a, b] и f(a)*f(b) < 0 => ∃c ∈ [a, b], что f(c) = 0
Рекурсивно делим отрезок пополам и смотрим значение в середине: если 0 - ок, если нет, то берем тот отрезок, на концах
которого f принимает значения разных знаков. Получим набор вложенных отрезков, длина которых = (b-a)/2^n -> 0. По т. Кантора,
существует ровно одна точка с общая для этих отрезков. Докажем, что f(c)=0:
От противного, пусть f(c)>0, например. Тогда существует окрестность точки с, в которой f > 0. Половинным делением мы когда-нибудь
загоним наш отрезок в эту окрестность => противоречие, ибо он разного знака на концах.

** 6) Дифференцируемость функции одного переменного, теорема Ферма, Ролля, Лагранджа и Коши
*** (Теорема Ферма) Если у функции в точке локального экстремума (в.г, нестрогого) существует производная, то она конечна и равна 0.
Рассмотрим максимум (минимум - аналогично). Запишем производную слева и справа по определению. Заметим, что эти пределы разных
знаков, но т.к. функция непрерывна в точке, то пределы слева и справа равны => оно может быть только 0.
*** Дифференцируемая функция на промежутке
Для каждой точки промежутка существуют конечные производные, а для концов - если они пренадлежат - соответствующие односторонние 
производные.
*** Дифференцируемая в широком смысле функция на промежутке
    То же самое, только производные м.б. +-∞
*** (Теорема Ролля) Если функция непр. на [a,b], дифф на (a, b) и f(a) = f(b) то ∃x ∈ (a, b) что f'(x) = 0
На отрезке достигается минимум и максимум (2 т.В). Если на границах - то функция константа и подойдет любая точка. Если нет,
то ∃x, что f(x), допустим, sup. Тогда по т. Ферма f'(x) = 0.
*** (Теорема Коши) f, g - непр. на [a, b], f - д.в.ш.с на (a, b), g - дифф на (a. b), причем g'(x) ≠ 0, то ]x: (f(b)-f(a))/(g(b)-g(a) = f'(x)/g'(x)
Расcм: ϕ(x) = f(x)+λg(x), λ ∈ R. Подберем λ так, что ф(а)=ф(b). => λ = - (f(b)-f(a))/(g(b)-g(a)). g(b) ≠ g(a) нигде, ибо иначе бы
по т.Ролля где-нибудь была бы ненулевая производная. ф - непр и дифф в широком смысле, ибо лин.к. дифф(g) и д.в.ш.с(f).
В общем, мы в условиях т. Ролля для ф(x) => ∃t: ф'(t)=0 = f'(t) + λg'(t) => λ = -f'(t)/g'(t) => то, что надо.
*** (Теорема Лагранджа) f - непр. на [a, b], д.в.ш.с на (a, b) => ]t: f(b)-f(a) = f'(t)(b-a)
Верно по т. Коши для g(x) = x.

** 7) Тейлор для одного действительного переменного
*** Формула Тейлора
это не буду переписывать, и так знаю
*** (Остаток в форме Пеано: корректность) (r_n(f, x) = o((x-x0)^n) при x→x0
Л1) P'n(f, x) = Pn-1(f', x), r'n(f, x) = r(n-1)(f',x) - раскрывая в лоб
Л2) P^(k)_n(f,x0) = f^(k)(x0), r^(k)_n (f, x0) = 0 - первое исходя из того, что ∑(j=k..n) не 0 только при j=k. Второе отсюда же.
Т) По индукции. Пусть f имеет конечную производную в т. x0 до n+1 включительно, и при этом для n мы знаем утверждение теоремы.
Т.к. f имеет конечную n+1 произв, то f' имеет конечную n произв => по предп. индукции r(f', x) = o((x-x0)^n).
Т.к. f имеет конечную n+1 произв, то в некоторой окр. x0 она непр, + дифф в x0 => r_(n+1)(f, x) -дифф в x0 (как разность f и P)
Зафиксируем точку х и применим теорему Лагранджа на [x, x0] (или [x0, x], смотря что больше). Получим f(x)-f(x0) = r'(e)(x-x0)
e зависит от x, поэтому оно e(x). Так же e(x)->x0 при x->x0 (т.о 2 маж). Дальше хитрый переход на стр. 165.  
*** (Остаток в форме Пеано: наилучшее приближение) Если f = Q + o((x-x0)^n) при x→x0, то Q = Pn(f,x) 
по предыдущей теореме, f = Pn + o(..). Тогда T = P-Q = o((x-x0)^n). Докажем, что это нулевой многочлен.
Т.к. оно o(...^n), то lim(T(x+t))/t^n)->0 при t->0 => T(x+t)->0 при t->0 => a0 = 0. => T = a1*t + ...+an*t^n
Разделим на t, получим что a1 = 0 и так далее занулим все коэффиценты.
*** Остаток в форме Лагранджа
** 8) Предел, непрерывность, ч.пр. и дифференцируемость функции нескольких переменных.
*** (Предел функции нескольких переменных по Коши) Все то же самое, только x, a ∈ R^m, | | - норма в R^m
*** (Предел функции нескольких переменных по Гейне) То же самое, только посл-ть ∈ R^m и сходится по норме. 
*** (Предел функции в точке по множеству) 
По Гейнe: a-пр.т.X, ∃U(a) f-опр на U∩X, тогда limF(x)=b при x->a,x∈X := вып-cя ∀xn∈X: limxn=a, xn≠a 
По Коши: то же самое, что и обычное определение, только x∈U(a)∩X
*** (Непрерывность) f - непр-а в а, если опр. в нек. окр. а и limf(x)->f(a) при x->a
*** (Непрерывность на мн-ве) то же самое, только предел по множеству.
Изолированная точка - непрерывна по определению
*** (т. о промежуточных значениях) Непр. функция принимает все значения между значениями в начале и конце.
f(x1)=y1, f(x2)=y2. x1,x2 ∈ G - откр. Рассмотрим кривую Г ∈ G, соединяющую x1 и x2: Г=(a1(t), a2(t)...an(t)), t∈[a,b].
ф(t) = f(a1(t),...an(t)) - непр на [a, b], ф(а)=y1, ф(b)=y2 => по аналогичной теореме для функции одной переменной все работает.

*** (обобщение т. Вейерштрасса 1,2) f - непр на компакте ограничена на нем и достигает своих sup и inf.
доказательство ровно такое же, с точностью до замены модуля на норму и R на R^m
*** (Частная производная)f: опр в окр. x0  и имеет кон. произв. в x0 f'x в точке (x0, y0) = df(x, y0)/dx в т. x0
*** (Дифференцируемая ф-я)f - дифф в x0 ∈ R^m, если можно представить: δf(x0) = f(x0+δx) + A(δx) + α(δx)*|δx|
А - линейная часть - дифференциал - df(x0)
α - бм при δx->0 
*** (НУ Дифференцируемости) f - дифф в x0 => 1) f - непр в x0, 2)∀(i=1..n) ∃кон. ч.пр. df/dxi(x0)
1) следует из того, что при δx->0 f(x0+δx)->f(x0) - опр. непрерывности
2) (док-во для сущ. ч.пр. по первому аргументу)
Зафиксируем δx = (δx1, 0, 0, ...) и перепишем b(δx1) = α(δx1, 0 ...)*sign(δx1) (заметим, что b(δx1)->0)
 => производная перепишется в виде: f(x0 + δx, x1,....) = f(x0, x1...) + A1*δx1 + b(δx1)*δx1. Перенесем f, разделим на δx1 и
устремим его к 0 => получим производная = A1 по определению
*** (ДУ Дифференцируемости) есть ч.пр по всем переменным, и все непр в x0 => f - дифф в x0.
Распишем δf(x0, y0), сделаем +-f(x0+δx, y0), применим т. Лагранджа для x и y, получим = f'x(x~, y0)*δx + f'y(x+δx, y~)*δy. (*) 
Заметим, что при δ(x,y) -> 0 x~->x0, y~->y0. => f'x(x~, y0)->f'x(x0, y0) = A (в силу непрервыности) // для f'y = B - аналогично
Подставим в (*), получим δf = (A*δx + a(δx)*δx) + (B*δy + b(δy)*δy). Мелкие = o(p) => определение дифференцируемости
** 9) Равномерная непрерывность функции на мн-ве, теорема Кантора
*** Равномерно-непрерывная функция: Если ∀e>0 p(x1 x2)<δ => |f(x1)-f(x2)|<e
*** (т. Кантора) f - непр. на компакте, равномерно-непрерывна на нем
От противного: пусть не равномерно-непрерывна, тогда существует e, что какие-бы δ: p(x1,x2)<δ мы не взяли, |f(x1)-f(x2)|>e
Будем подставлять δ=1, 1/2, 1/3, получим {x'k}, и {x''k}, что p(x'k, x''k)<1/k но |f(x'k)-f(x''k)| >  e.
Огр полследовательность x'k имеет сх. подпосл x'kk, которая сходится к x0∈G (ибо либо внутренняя, либо гр, но границы входят в компакт)
x''k тоже имеет сх подпосл x''kk
p(x''kk, x0) по пр. треуг ⩽ p(x''kk. x'kk) + p(x'kk, x0) = 1/k + 0 (при k->∞) => limx''kk->x0 => lim(p(x''k-x''kk))->0 при k->∞
Противоречие, ибо для подпоследовательностей, как для части последовательности, p(x''k-x''kk)>e.

** 10) Определенный интеграл Римана одного переменного, критерий интегрируемости Дорбу.
*** Разбиение отрезка R - оно же дробление
*** Дробления упорядочены с помощью ∈: R1>R2 если все точки R2 присутствуют в R1 и еще добавили новые
*** R = Max(R1, R2) := R1 ∪ R2. Естесственно, R > R1, R > R2
*** Дальше все делается для функции f, ограниченной на [a, b]:
*** Mi = supf(x) на [xi, x(i-1)]. mi - inf, wi = Mi-mi - колебание ф-ции на отрезке.
*** Верхняя сумма Дорбу: S*_R := ∑Mi*δxi, Нижняя S_*R := ∑mi*δxi, wR = S*_R-S_*R
*** Лемма: R1>R2 => S*_R1 ⩽  S*_R2, S_*R1 ⩾ S_*R2, w_R1 ⩽ w_R2
Доказываем 1. Второе - аналогично, третье - как разность первого и второго.
По индукции: докажем, что верхняя сумма уменьшится при добавлении одной точки в дробление. Это очевидно: мы раздробили один 
отрезок новой точкой пополам, тогда теперь у половинок ступенек супремумы стали разные, а раньше был общий => одна из них не 
увеличилась.
*** Верхний интеграл Дорбу I* := инфиум верхних сумм. Нижний I_* := супремум нижних.
*** Если I*=I_* => f - интегрируема по Риману, а значение I* - определенный интеграл Римана функции f на [a, b]
*** (Критерий интегрируемости Дорбу)
Равносильно:
1) f - интегр. по Риману на [a,b]
2) ∀e>0 ∃R: wR<e
3) ∀e>0 ∃δ ∀R: мелкость < δ => wR<e

3=>2 - очевидно
2=>1 - wR = S*-S_*<e а верхний и нижний интегралы Дорбу зажаты между суммами => интегралы стремятся друг к другу => интегр по риману 
1=>2 - Возьмем дробление R1 такое, что верхняя сумма отстает от интеграла не более, чем на e/2. Возьмем R2 для нижней суммы так же
Возьмем R := max(R1, R2), при R верхняя и нижняя сумма приблизятся к графику сильнее => не вылезут за I+-e/2. Отнимем дробления
друг от друга, получим то, что надо.
2=>3 У нас есть, что ∀e>0 ∃R: wR<e → ∀e ∃ R0: wR0 < e/2  
Пусть δ0 - мелкость дробления R0, N0 отрезочков внутри. Возьмем новую δ := min(δ0, e/4MN0). Возьмем R - произвольное дробление с 
мелкостью не больше δ. Наложим R1 на R0. Часть отрезочков R1 точки R0 разрубят на 2 части (таких не более N0-1). Рассмотрим 
wR1 = ∑wi*δxi = ∑' (по всем целым из R1) + ∑'' (по всем, которые разрубило точками из R0). Оценим сумму.
1) Рассмотрим R = max(R1, R0). R>R0 => wR ( = wR1 на ∑') ⩽ wR0 < e/2.
2) ∑'' < ∑(число столбиков = N0)*(макс. длину = δ)*(макс. wi = Mi-mi < 2M) = e/2.
Сумма меньше e. ЧТД.
** 11) Криволинейный интеграл первого и второго рода функции нескольких действительных переменных.
*** Интеграл 1 рода
Пусть Г - гладкая кривая r(t) = (x(t), y(t), z(t)), t ∈ [a,b], G ∈ R^3, Г ∈ G. f - непр на обл. G. 
Тогда криволинейным интегралом 1 рода ∫гf( x,y,z)ds наз-ся определенный ∫ Римана: ∫(a,b)f(x(t),y(t),z(t))*|r'(t)|dt.
*** Допустимая замена параметра в кривой
Пусть кривая Г параметризуется двумя способами: (x1(t),y1(t),z1(t)) t ∈ [a,b] и (x2(u),y2(u),z2(u)), u ∈ [α,β]. При этом u(t) - 
это непрерывно дифференцируемая функция на [a, b], отображающая [a, b] на [α, β], то такая замена называется допустимой.
*** (Корректность) Значение ∫ не изменится при ДЗП
У нас есть ДЗП ровно такая, как выше. Замена взаимооднозначна по т.Б-К (многомерная): u' либо >0 везде либо <0 везде.//недопонял 
Выпишем два интеграла для обоих путей. Потом во второй (который c u) поставим замену u->u(t), t∈[a,b]. Выпрыгнет u'(t)dt в конце
и +- перед ∫ - + соответствует u'(t)>0, минус - u'(t)<0. 
Соответственно, запихиваем безболезненно u'(t) под модуль и получаем первый интеграл.
*** Свойства ∫ 1 рода - линейность и аддитивность по кривой
**** Ориентация кривой - гладкая кривая ориентирована, если задан единичный вектор r(t) - непр на [a,b] 
то есть если сделан выбор знака в равенстве r = +-r'(t)/|r'(t)|
*** Кусочно гладкая кривая
кривая, на всех своих кусках гладкости ориентированная так, что конец i-1 куска - это начало i куска. 
*** Интеграл второго рода
Пусть Г - ориент. гладкая кривая (r(t) - ед.век.кас.к Г, он же - ориентация Г), G ∈ R^3, Г ∈ G. a:G ∈ R^3->R^3 - непр.
Тогда криволинейным интегралом второго рода ∫г(a, dr) наз-ся интеграл первого рода ∫г(a,r)ds.
Этот интеграл можно переписать в виде: ∫P(x,y,z)dx + Q(x,y,z)dy + R(x,y,z)dz. Выведем формулу: простая параметризация:
= +- ∫(P(x(t), y(t), z(t))*x'(t) + Q(-//-)*y'(t) + R(-//-)*z'(t))dt на [a, b]
+ если с возрастанием t точка движется по кривой в нужном направлении, - если в противоположном.
** 12) Несобственный интеграл функции одного действительного переменного. Критерий Коши и признаки для знакопостоянных и знакопеременных функций
***  Несобственный интеграл
f: [a,b(мб ∞))->R, и интегрируема по Риману на любом отрезке [a, b'], где a < b' < b. Тогда если ∃ конечный lim∫(a,b')fdx при b'->b-0
то тогда эта штука называется несобственным интегралом на [a,b), а f наз-ся несобственно интегрируемой там же.
*** (Формула Ньютона-Лейбница) ∫f на [a,b) = F(b-0)-F(a)
Сходимость интеграла равносильна конечности предела, в случае его наличия оба предела конечны и равны
*** (Критерий Коши) пусть f - интегрируема по Риману на ∀[a, b'] где a<b'<b. Тогда ∫[a,b)fdx сходится <=> ∀e>0 ∃δ>0
что ∀ b' и b'' из δ-окр(b) |∫(b', b'')fdx|<e. 
Рассмотрим F(x) = ∫(a,x)f(t)dt. Интеграл сходится limF(x)<∞ при x->b-0 => это обычный критерий Коши существования предела в b.
*** (Безымянная теорема) f -//- и f ⩾ 0 на нек. U(b-0). Тогда интеграл сх <=> F(x) = ∫[a,x)f(t)dt - огр на [a,b).
НУО можно сказать, что f⩾ 0 везде, ибо при анализе сх. мы можем переставить нижний предел в часть, где она точно положительна - 
нас интересует только верхний предел. Но тогда F(x) - возр(мб нестрого) => по теореме о пределе монотонной функции ограниченность
f равносильна наличию конечного предела F к b-0, то есть сх. ∫f.
*** (Признак сравнения)f,g ⩾ 0 если f = O(g), то сходимость первого влечет сходимость второго, расходимость второго - расх. первого.
Как и в прошлом, считаем, что 0 ⩽ f ⩽ g на всем [a,b). Тогда сх-ть интеграла по g равносильно огр-ти G(x) из предыдущей леммы.
Но т.к. 0 ⩽ ∫f ⩽ ∫g на любом подотрезке, то F - огр => ∫f - сх.
Еще в довесок. Если f ~ g на [a,b), то они сх и расх. одновременно. - следует из предыдущей леммы, ибо f~g <=> f=O(g) ∩ g=O(f)
*** (Признак Дирихле) 
f - непр и имеет огр. первообр на [a,b), g - непр. дифф и монотонно -> 0 => ∫[a,b)f*gdx - сх.
Рассмотрим интеграл на [b', b''] a ⩽ b'< b'' < b Проинтегрируем по частям, вынесем F как M - мажоранта (огр). Останется ∫ =
= 2*M*g(b') -> 0 => расписываем определение предела по Коши для 2*M*g(b') => получаем критерий Коши для сходимости интеграла.
*** (Признак Абеля)
f - непр и ∫[a,b) - сх. g - непр. дифф, огр и g' не меняет знака => ∫[a,b)f*gdx - сх.
Пусть g - убывает (иначе возьмем -g и припишем - к ответу). g - монотонна и огр на [a,b) => ∃ кон. limg(x) = C при x->b-0.
Рассм g1(x) = g(x)-C - монотонно стремится к 0. F имеет огр первообразную по безымянной теореме выше => Мы в условиях Дирихле
** 13) Числовые ряды, критерий Коши, признаки сходимости для знакопостоянных и знакопеременных рядов.
*** Частичные суммы, остаток ряда - все как обычно
*** (НУ сходимости ряда) ∑un - cх => limun->0
Следует из того, что un = Sn+1-Sn => предельный переход.
*** (Критерий Коши) ∑un - сх <=> ∀e>0 ∃N, ∀p ∈N |∑(N, N+p)un|<e
Следует из критерия Коши для наличия предела последовательности. 
*** (Безымянная Т) Сумма модулей сходится => ряд сходится.
Банально потому, что сумма модулей больше.
*** Ряд с какого-то места положителен => сходимость ряда равносильна ограниченности частичных сумм
До положительного куска - роли не играет. После - частичные суммы возрастают => ограниченность ряда сумм эквивалентна наличию
предела (по т. Вейерштрасса) => эквивалентна сходимости суммы в пределе на ∞.
*** Если un = O(vn) на ∞, то ∑un-cx -> ∑vn - cx. расх - наоборот.
НУО: 0 ⩽ vn ⩽ С*un далее очевидно
*** (Интегральный признак сравнения) f - неотр и монотонна на [a,+∞) => ∫[a, +∞) - сх <=> ∑[a, +∞] - cх
если возр, то либо f==0 -сх, либо limf=С расх, либо limf = ∞ - расх
если уб, то либо limf = C - расх, либо limf = -∞ - расх, либо limf = 0 - содержательный случай

// Здесь должна быть та самая картинка с графиком и столбиками с твоего второго семака
Очевидно, что функция зажата между "нижними" и "верхними" ступеньками - т.е. между суммами "по левому" и "по правому" краю
ступенек.  Если ∫f - сх, то ∑ нижних ступенек сх, => можно делать предельный переход - сумма сх.
Если ∑ - сх, то ч. суммы сх => ∫[a, N) - огр ∀N => предельный переход по N.
*** (Признак Даламбера) un ⩾ 0: если НСНМ u(n+1)/un <= q < 1 - cх, ⩾ 1 - расх. Предельный: lim(u(n+1)/un) < 1 - сх, ⩾ - расх.
Обычный: 
1) q<1: то u(n+1) <= q*un <= q^2*u(n-1) => un ⩽ u1*q^(n-1) => ∑q^(n+1) - сх => ∑un -> сх // посмотреть у Даши
2) q>=1 - посл НСНМ возр => не выполн НУ сходимости
Предельный:
1) Возьмем q' ∈ (q, 1) НСН n0 ∀n>n u(n+1)/un < q' - работает предыдущая теорема
2) НСНМ u(n+1)/un > 1+e => работает предыдущая теорема
*** (Признак Коши) un ⩾ 0: НСНМ n√un <= q < 1 - сх, >= 1 - расх. Предельный - аналогично.
1) un ⩽ q^n => сходится ибо ∑q^n - сх
2) возр - не вып НУ сходимости
Предельный - как в Даламбере
*** (Признак Дерихле для знакопеременных)an, bn:  Sn(a) - огр, Sn(b) - монотонно -> 0. Тогда ∑ab - сх.
Аналогично Дерихле для несобственных интегралов, только вместо интегрирования по частям - преобразование сумм Абеля. // Выучить это говно
*** (Признак Абеля для знакопеременных)an, bn: ∑a - cх, bn - монотонна и огр, тогда ∑ab - сх.
Аналонично Абелю для интегралов (заменяем на b1-C и сводим к Дерихле)
*** (Признак Лейбница для знакопеременых) bn ⩾ 0 - монотонно -> 0 => bn*(-1)^n - сх.
Рассмотрим "суммы через одно": S_2n - убывает, S_(2n+1) - возр. Пусть они имеют пределы α и β соответственно. Они не ∞, ибо они 
разных знаков (иначе бы bn не -> 0)
Т.к. их разность -> 0, то α=β. 
А дальше какая-то простая химия на стр. 200, которую я не понял => Sn -> a.
** 14) Функциональные последовательности и ряды, признак Коши и т. Вейерштрасса равномерной сходимости на множестве
*** Поточечная сходимость ф.п: ∀x ∃limfn(x) = f(x)
Для любого x существует е-корридорчик, что начиная с какого-то N |fn-f| < e
*** Равномерная сходимость ф.п: ∀e>0 ∃n0, ∀n>n0 ∀x |fn(x)-f(x)|<e
Для любого e-корридорчика начиная с какого-то N все функции окажутся в нем
*** (Критерий Коши р.сх.ф.п) fn ⥤ f <=> ∀e>0 ∃n0 ∀n,m>n0 ∀x |fn(x)-fm(x)|<e // эдакая фундаментальность для ф.п.
=> стандартный ход: НСНМ |fn-f|<e/2 и |fm-f|<e/2 => оценим разность сверху суммой => то, что надо.
<= исходя из данного есть поточечная сх => limfm -> f при m -> ∞.
Перепишем то, что дано и устремим m к ∞. Получится ровно определение равномерной сходимости.
*** (Перенос непр) Пусть fn ⥤ f, все fn - непр на E => f - непр на E.
Док-во есть, но я забил. //Восстановить
*** Функциональный ряд (ф.р) ∑un(x) - равномерно сх. на мн-ве E, если посл-ть его частичных сумм Sn равномерно сходится на E.
*** (Критерий Коши р.сх.ф.р) ∑un(x) - р.сх на E <=> ∀e>0 ∃n0, ∀n,m>n- ∀x |∑(i=n..m)un(x)|<e.
Доказано, ибо это КК для р.сх.ф.р. относительно Sn(x) - ф.п.
*** (НУ р.сх.ф.р) ∑un(x) - р.сх. на E => un(x) ⥤ 0 на E
Т.к. Sn-1(x) и Sn(x) ⥤ S, и при этом un(x) - их разность, то отнять одно от другого и получим то, что надо.
*** (Критерий Вейерштрасса - ДУ р.сх.ф.р) un(x) по модулю ∀x ∀n мажорируется сходящимся числовым рядом => un(x) - р.сх. на E.
Выпишем критерий Коши сходимости числового ряда, возьмем оттуда ∑(i=n..m)a. Оно мажорирует такую же сумму un(x) при всех х =>
получили КК р.сх. ф.р.
** 15) Степенные ряды, теоремы Абеля и ряд Тейлора для ф-ции одного действительного переменного
*** Степенной ряд - ф.р: ∑(n=0..∞)an(z-z0)^n
*** (Первая т.Абеля)  если ст.р. сх при z1 ≠ z0, то ∀z2: |z2-z0|<=|z1-z0| ряд абс. сх в z2.
Ряд сходится => ряд -> 0 при n->0 (НУ сх.ф.р). 
Домножим и разделим ряд в т. z2 на |z1-z0|^n, вынесем дробь из z, она = o(q^n) где q = |z2-z0|/|z1-z0| < 1. Итого ряд сх. по
признаку сравнения
*** Радиус сх. R степенного ряда  - ∀z: |z-z0|<R - ряд cх, ∀z: |z-z0|>R - ряд расх. 
*** (Вторая т.Абеля) ряд сх в z1 => ряд равномерно сх. на отрезке [z0,z1]
Естесственно, что z1 или внутри или на границе круга, я не знаю почему это поясняют в условии. Но да ладно.
Параметризуем отрезок как z = z0 +t(z1-z0), t∈[0,1]. Домножим и разделим ряд на |z1-z0|^n, подставим вместо z параметризацию,
посокращаем, получим ∑an(z1-z0)^n*t^n. Ряд без t^n - сходится, ибо z1 - константа в круге,а t^n - монотонен и огр (константа
при t=0 или 1 и -> 0 при всем остальном.) По признаку Абеля для рядов оно равномерно сх на t∈[0,1] => на z∈[z0,z1].
*** Тейлор - протрахан (я не знаю что именно от меня хотят)
** 16) Матрицы, определитель и ранг матрицы, теоремы о базисном миноре и о ранге матрицы. 
*** 
