* Матан
** 1) Предел числовой последовательности, теорема Вейерштрасса о пределе монотонной последовательности
*** [#A] Определение предела, определение отрицания предела
    Стандартное, через e. Отрицание предела - ∃e>0 что за него последовательность хоть где-то да выйдет
*** Лемма о единственности предела последовательности
    a и b - два предела одной последовательности. Рассмотрим непересекающиеся окрестности - когда-нибудь последовательность зайдет
    и туда и туда, что бред
*** Последовательность ограничена с n0 → ограничена везде
    После ограничена, а до - возьмем супремум и инфиум конечной части
*** Сходящаяся последовательность ограничена
    Начиная с какого-то n для ϵ = 1 по определению оно огр. a ⨦ 1, поэтому верно по предыдущей лемме.
*** Последовательность нснм по модулю больше половины своего предела, причем с сохранением знака
    a > 0 - предел. Рассмотрим ϵ = a/2. По определению - раскроем модуль и получим то, что надо. Потом для a < 0 так же.
*** Лемма о сохранении знака - знаки предела и посл. совпадают начиная с какого-то n
    прямо следует из предыдущей
*** Определение бесконечно-малой последовательности (бмп). Любую посл. м. представить как сумму ее предела и бмп.
    рассмотрим бмп = последовательность - предел. Покажем по опр, что она - бмп.
*** [#B] бмп + бмп = бмп.
    для любого ϵ можем выбрать общий (max) n0, что они обе меньше ϵ\2. => сумма < ϵ
*** бмп * огр = бмп, бмп*С = бмп, бмп*бмп = бмп
    1) пусть огр < C, тогда бмп нснм < ϵ/c. => произведение < ϵ
    остальное сразу следует из 1.
*** Предел суммы, произведения и частного (b != 0) равен сумме, произведению и частному пределов
    Везде сначала раскладываем последовательность на сумму предела и бмп, потом 
    1) a + b + бмп = a+b
    2) все - бмп, кроме a*b
    3) Берем n после которого yn != 0. Пишем xn/yn -a/b, выносим 1/yn, получаем огр*бмп.
*** (предельный переход в неравенстве) Если нснм xn <= yn, то и a <= b.
    1) от прот: рассм. непересекающиеся окр. a и b. нснм последовательности зайдут в свои окрестности и будет противоречие: xn>yn.
*** (Лемма о двух мажорантах) limXn = limYn = a, Xn <= Yn <= Zn => limYn = a.
    Фиксируем e. Тогда рассмотрим n, когда Xn и Zn уже в этой окр. Соответственно, Yn тоже зажата м-у a-e и a+e начиная с этого n =>
    limYn = a по опр.
*** [#A] (Т. Вейерштрасса) монотонно возр и огр сверху => имеет предел равный sup. // Аналогично для убывает и inf
    Рассм. α = supXn. ∀e > 0 ∃n ∀nk > n: a-e < Xnk ⩽ a (ибо возр). => нснм Xnk ∈ Ue(a) => a - предел по опр.

** Вспомогательные штуки
*** Теорема Кантора о вложенных отрезках: вложенные отрезки имеют как минимум одну общую точку. А если их длины убывают - единственную.      
    Влож отрезки: ...[an, bn] ∈ ... [a1, b1] → a1 <= a2 <= .. <= an ... <= bn <= ... <= b1. Рассмотрим посл. {an} и {bn}. 
    an огр. сверху любым b, bn огр снизу любым a => существуют supAn = γ1 и infBn = γ2. [γ1, γ2] - пренадлежит всем отрезкам.
    Теперь, если |an - bn| → 0 => an ⫹ γ1 ⫹ γ2 ⩽ bn => γ1 = γ2 = γ = limAn = limbn по т. Кантора
 
*** 6 стандартных предельных символов (6 СПС)
a, a+0, a-0, +∞, -∞, ∞
** 2) Частичный предел числовой последовательности. Теорема Больцано-Вейерштрасса
*** [#A] Опр. частичного предела последовательности Xn
a - ч. пр, если ∃ Xnk - строго возр подпосл. такая, что limXnk = a.
*** Предел любой подпоследовательности равен пределу последовательности, если он есть
Рассматриваем U(a ∈ СПС). Внутри - если посл зашла, то подпосл тоже. Вне окр - конечное число эл-тов.
Следствие - если предел ∈ R, то он же - единственный ч. пр.
*** (Критерий ч.пр) a ∈ (R, +∞, -∞) - ч.пр. Xn <=> в любой Ue(a) Xn ∃ беск. число членов Xn
=> Если оно ч.пр, то вне любой окрестности содержится не более, чем конечное число членов ряда => внутри окрестности все остальные(∞)
<= Строим подпосл: Xk1 ∈ U1(a), xk2 ∈ U_1/2(a) ... т.к. в любой окр содержится ∞ членов, то мы всегда возьмем один - беск посл
со строго возр. индексами. Т.к. Xkt ∈ U_1/t(a) => a - 1/t ⩽ Xkt ⩽ a + 1/t => по лемме о двух мажорантах limXkt = a. 
Для беск. нужно брать //доделать 
*** [#A] (т. Больцано-Вейерштрасса) Любая огр. посл. имеет сх. подпосл.
Xn - огр => лежит в отрезке [a, b]. Разобьем отрезок пополам и возьмем ту половину, где Xn - бесконечно много (если в обоих
бесконечно много - то любую). И так рекурсивно. μ[An, Bn] = (b-a)/2^n -> 0 => по т. Кантора есть ровно одна общая точка c.
Фиксируем e. Т.к. ∃n0, что ∀n>n0 μ[An, Bn] < e (=> ∈ Ue(c)), причем там ∞ Xn, то по критерию ч.пр. с - частичный предел.
*** (о единственном ч.пр) Xn - огр и имеется ровно 1 ч.пр. =a, то Xn -> a. 
Xn - огр => Xnk => огр => a ∈ [m, M]. Пусть a - не предел Xn, =>  ∃ e>0, что вне Ue(a) б.м. членов Xn (пусть справа) => по ТБВ
на [a+e, M] имеется частичный предел => противоречие тому, что он один.
** 3) Критерий Коши сходимости последовательности
*** (Критерий Коши) Xn - сх <=> Xn - фунд.
=> пусть a - предел. Фиксируем e, тогда ∃n0, что | | < e/2. Берем n>n0 и m > n0: |xn -xm| = |(xm - a) + (a - xm)| <... < e.
<= Докажем, что оно огр: фиксируем e = 1, тогда ∃n0, ∀n, m ⩾ n0 |xm - xn| < 1 Фиксируем m = n0 => |xn| ... < 1 + |xn0| => огр 
начиная с n0 => огр везде => по ТБВ ∃ ч.пр. Чтобы доказать, что он - предел всей Xn, докажем, что он один. 
От противного, пусть их два: b > a. Пусть e = (b-a)/3 (из опр. фунд) => ∃n0, что |xn - xm| < e. Но т.к. вокруг каждого предела
бесконечно много элементов Xn, то найдутся n1, n2 > n0, что Xn1 ∈ Ua, Xn2 ∈ Ub => противоречие, ибо между окрестностями зазор > e.

** 4) Опеределения предела функции по Коши и по Гейне, их эквивалентность. Критерий существования предела по Коши. 
*** Определение по Коши 
limf(x) = b при x->a :=  ∀e > 0 ∃δ(e)>0 |x-a| < δ => |f(x) - b| < e
*** Определение по Гейне
-//- := ∀Xn: limXn = a => limf(Xn) = b при n -> ∞
*** Эквивалентность Коши и Гейне
=> Возьмем {Xn} такую, что limXn = a (xn ≠ a). Зафиксируем e, подберем такой номер n0, что ∀n>n0 |xn-a| < δ. Но из этого следует,
что |f(xn) - b| < e. В силу произвольности Xn, это предел по Гейне.
<= Возьмем отрицание Коши: существует e, что какую бы δ мы не взяли, найдется U(a), что f(x) !∈ U(b)
Пусть δ = 1/n => есть {Xn}, что ∀n ∈ N Xn в 1/n-окрестности a, но при этом f(Xn) вне e-окрестности b. По лемме о двух мажорантах, 
limXn = a => по гейне limf(xn) = b. Делаем предельный переход - получаем противоречие.
*** Много переходных лемм, аналогичных билету 1.
Доказательства в духе: возьмем рандомную подпоследовательность, воткнем ее в наши функции и рассмотрим это как новые последовательности.
По соответствующим леммам, для последовательностей работает => для функций работает в силу рандомности последовательностей.
*** (Критерий Коши существования предела функции) Функция имеет предел b в точке a <=> функция "фундаментальна в точке a"
=> Из предела по Коши берем x1 и x2 из δ-окрестности такие, что |f(x1 и x2) - b| < e. Дальше |f(x1)-f(x2| = |f(x1) - b.... | <...<e   
<= Возьмем Xn такой, что limXn = α и покажем, что f(xn) - фундаментальна (используя усл-е) => имеет предел.
Теперь докажем, что произвольно взятые Xn будут иметь один и тот же предел. Пусть нет: Xn->α, Yn->α, но f(Xn)->a, f(Yn)->b. 
Склеим Xn и Yn (x1, y1...) , получим Zn -> α. Но у него не будет предела, ибо есть два частичных предела. Противоречие.

** 5) Свойство непрерывной функции на отрезке, т. Вейерштрасса и Больцано-Коши
*** Что такое свойства?
*** Непрерывность на отрезке [a, b] => непрерывность во всех точках интервала (a, b), непрерывна справа в a, и слева в b
*** (Первая т. Вейерштрасса) f - непр. на [a, b] => f - огр на [a, b]
Пусть это не так: тогда ∀e>0 ∃x ∈ [a, b] f(x) > e. Будем подставлять e = 1, 2, 3..., получим {xn} такую, что |f(xn)|>n. 
Xn ∈ [a, b] - огр, тогда ∃Xnk - сх. (пусть к точке x0 ∈ [a, b] т.к. xnk ∈ [a,b]). f - непр => lim(f(Xnk)) = f(x0). Но, при этом, 
f(Xnk) > nk >=k (как возр. индексы подпосл). => f(Xnk) -> ∞ при k -> ∞. Противоречие.
*** (Вторая т. Вейерштрасса) f - непр. на [a, b] => f достигает своих sup и inf на [a, b]
Sup и inf существуют (ибо f - огр по Вейерштрассу1). Пусть sup = M. Тогда ∀M'<M ∃x: f(x)>M'. Будем подставлять M' = M-1/n, 
получим последовательность Xn ∈ [a, b] => ∃ Xnk - сх к X0. но т.к. ф-я непрерывна в x0, то limf(Xnk) = f(x0) при k->∞. 
Но f(Xnk)->M, так что f(x0) = М в силу единственности предела.
*** (т. Больцано-Коши) f - непр. на [a, b] и f(a)*f(b) < 0 => ∃c ∈ [a, b], что f(c) = 0
Рекурсивно делим отрезок пополам и смотрим значение в середине: если 0 - ок, если нет, то берем тот отрезок, на концах
которого f принимает значения разных знаков. Получим набор вложенных отрезков, длина которых = (b-a)/2^n -> 0. По т. Кантора,
существует ровно одна точка с общая для этих отрезков. Докажем, что f(c)=0:
От противного, пусть f(c)>0, например. Тогда существует окрестность точки с, в которой f > 0. Половинным делением мы когда-нибудь
загоним наш отрезок в эту окрестность => противоречие, ибо он разного знака на концах.

** 6) Дифференцируемость функции одного переменного, теорема Ферма, Ролля, Лагранджа и Коши
